### ISSUE TITLE
How to read configuration in ConfigMap using spring-cloud-starter-kubernetes-client-config?

### ISSUE THREAD

**Issue by a11enhuang** [spring-cloud/spring-cloud-kubernetes#1014]
Spring Boot Version: 2.6.7
Spring Cloud Kubernetes Version: 2.1.2
Maven dependency:

```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-client-config</artifactId>
</dependency>
```

When I try to use spring-cloud-starter-kubernetes-client-config to help me with configuration management, my bootstrap.yaml is configured like this:
```yaml
spring:
  application:
    name: xxx
  main:
    cloud-platform: kubernetes
  cloud:
    kubernetes:
      config:
        name: ${spring.application.name}
        namespace: microservices
        sources:
          - name: ${spring.application.name}
      reload:
        enabled: true
        mode: event
```
When I run the application outside the cluster such as IDEA, I have to configure spring.main.cloud-platform=kubernetes to try to read the configuration in ConfigMap.

However, when the project starts I get the following error:
```txt
2022-05-13 18:02:45.718  WARN 48466 --- [           main] [] ubernetesProfileEnvironmentPostProcessor : Not running inside kubernetes. Skipping 'kubernetes' profile activation.
2022-05-13 18:02:46.029  INFO 48466 --- [           main] [] o.s.c.k.c.KubernetesClientUtils          : Could not create the Kubernetes ApiClient in a cluster environment, because : 

java.lang.IllegalStateException: java.lang.NumberFormatException: null
	at io.kubernetes.client.util.ClientBuilder.setBasePath(ClientBuilder.java:262) ~[client-java-13.0.2.jar:?]
	at io.kubernetes.client.util.ClientBuilder.cluster(ClientBuilder.java:248) ~[client-java-13.0.2.jar:?]
	at org.springframework.cloud.kubernetes.client.KubernetesClientUtils.kubernetesApiClient(KubernetesClientUtils.java:43) ~[spring-cloud-kubernetes-client-autoconfig-2.1.2.jar:2.1.2]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration.apiClient(KubernetesClientAutoConfiguration.java:45) ~[spring-cloud-kubernetes-client-autoconfig-2.1.2.jar:2.1.2]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$cf08021b.CGLIB$apiClient$3(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.1.2.jar:2.1.2]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$cf08021b$$FastClassBySpringCGLIB$$e0dc537c.invoke(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.1.2.jar:2.1.2]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.19.jar:5.3.19]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.19.jar:5.3.19]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$cf08021b.apiClient(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.1.2.jar:2.1.2]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
```
And the console keeps prompting this error:

```txt
2022-05-13 18:02:57.182  INFO 48466 --- [s.V1ConfigMap-1] [] i.k.c.i.c.ReflectorRunnable              : class io.kubernetes.client.openapi.models.V1ConfigMap#Start listing and watching...
2022-05-13 18:02:57.184 ERROR 48466 --- [s.V1ConfigMap-1] [] i.k.c.i.c.ReflectorRunnable              : class io.kubernetes.client.openapi.models.V1ConfigMap#Reflector loop failed unexpectedly

java.lang.NullPointerException: null
	at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespacedConfigMapCall(CoreV1Api.java:28058) ~[client-java-api-13.0.2.jar:?]
	at org.springframework.cloud.kubernetes.client.config.reload.KubernetesClientEventBasedConfigMapChangeDetector.lambda$watch$0(KubernetesClientEventBasedConfigMapChangeDetector.java:110) ~[spring-cloud-kubernetes-client-config-2.1.2.jar:2.1.2]
	at io.kubernetes.client.informer.SharedInformerFactory$1.list(SharedInformerFactory.java:206) ~[client-java-13.0.2.jar:?]
	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:88) ~[client-java-13.0.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```
But when I replaced the dependency with fabric8-config, it worked perfectly even outside the cluster:
```xml
<dependency>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-starter-kubernetes-fabric8-config</artifactId>
</dependency>
```

Am I doing something wrong?

**Comment by ryanjbaxter** [comment]
The first error is purely informative that we couldn't construct an API client using the kubernetes config.

For the second error can you try setting `spring.cloud.kubernetes.client.namespace`?

**Comment by a11enhuang** [comment]
Why throw the first error? If spring.main.cloud-platform=none, the Kubernetes configuration does not appear to take effect, but enabling applications from outside the cluster is a normal requirement.
For the second error, I tried tweaking the configuration as suggested:
```yaml
spring:
  application:
    name: service-order
  main:
    cloud-platform: kubernetes
  cloud:
    kubernetes:
      config:
        name: ${spring.application.name}
        namespace: ${spring.cloud.kubernetes.client.namespace}
        sources:
          - name: global-config
      reload:
        enabled: true
        mode: event
      client:
        namespace: microservices
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans,trace
```
I see some warnings in the console:
```text
2022-05-14 16:38:05.769  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap custom-config-name1 was added.
2022-05-14 16:38:10.430  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
2022-05-14 16:38:10.431  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap custom-config-name2 was added.
2022-05-14 16:38:10.970  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
2022-05-14 16:38:10.970  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap kube-root-ca.crt was added.
2022-05-14 16:38:12.066  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
2022-05-14 16:38:12.066  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap custom-config-name3 was added.
2022-05-14 16:38:13.242  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
2022-05-14 16:38:13.243  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap custom-config-name4 was added.
2022-05-14 16:38:14.584  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
2022-05-14 16:38:14.584  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap custom-config-name5 was added.
2022-05-14 16:38:15.709  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
2022-05-14 16:38:15.710  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap custom-config-name6 was added.
2022-05-14 16:38:17.021  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
2022-05-14 16:38:17.022  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap custom-config-name7 was added.
2022-05-14 16:38:17.942  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
2022-05-14 16:38:17.943  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap custom-config-name8 was added.
2022-05-14 16:38:19.287  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
2022-05-14 16:38:19.288  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap custom-config-name9 was added.
2022-05-14 16:38:20.479  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
2022-05-14 16:38:20.480  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap custom-config-name10 was added.
2022-05-14 16:38:22.732  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
2022-05-14 16:38:22.732  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap global-config was added.
2022-05-14 16:38:23.280  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
```
And my local application still doesn't seem to be able to read the configuration in the ConfigMap. Why?
I have specified spring.cloud.kubernetes.config.sources.name=global-config in the configuration file, why is there a warning for another configuration name? It seems that all configurations under this namespace are showing up in the warning.

**Comment by ryanjbaxter** [comment]
So the configuration in `global-config` is not added as a property source?  Do you see it added in `/actuator/env`?

**Comment by a11enhuang** [comment]
I carefully confirmed that the `global-config` configuration information was successfully added to `/actuator/env`.

Why are these warnings:
```text
2022-05-14 16:38:05.769  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap custom-config-name1 was added.
2022-05-14 16:38:10.430  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
2022-05-14 16:38:10.431  INFO 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : CongifMap custom-config-name2 was added.
2022-05-14 16:38:10.970  WARN 49193 --- [pool-5-thread-1] [] sClientEventBasedConfigMapChangeDetector : Configuration change was not detected.
```
It seems that all ConfigMaps under the namespace appear in this warning, but I have clearly configured `spring.cloud.kubernetes.config.sources`

I suggest if the NumberFormatException can be hidden because it looks really unfriendly and I even thought something major went wrong with my program.
```text
2022-05-15 09:21:22.503  INFO 49676 --- [pool-5-thread-1] [] o.s.c.k.c.KubernetesClientUtils          : Could not create the Kubernetes ApiClient in a cluster environment, because : 

java.lang.IllegalStateException: java.lang.NumberFormatException: null
	at io.kubernetes.client.util.ClientBuilder.setBasePath(ClientBuilder.java:262) ~[client-java-13.0.2.jar:?]
	at io.kubernetes.client.util.ClientBuilder.cluster(ClientBuilder.java:248) ~[client-java-13.0.2.jar:?]
	at org.springframework.cloud.kubernetes.client.KubernetesClientUtils.kubernetesApiClient(KubernetesClientUtils.java:43) ~[spring-cloud-kubernetes-client-autoconfig-2.1.2.jar:2.1.2]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration.apiClient(KubernetesClientAutoConfiguration.java:45) ~[spring-cloud-kubernetes-client-autoconfig-2.1.2.jar:2.1.2]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$7703e56e.CGLIB$apiClient$2(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.1.2.jar:2.1.2]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$7703e56e$$FastClassBySpringCGLIB$$4fb56a40.invoke(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.1.2.jar:2.1.2]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.19.jar:5.3.19]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.19.jar:5.3.19]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$7703e56e.apiClient(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.1.2.jar:2.1.2]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.19.jar:5.3.19]
```

**Comment by ryanjbaxter** [comment]
I suppose that if specific config maps or secrets we monitor rather than monitoring all of them.

The `NumberFormatException` is really just a side effect of trying multiple ways to create the ApiClient..its purely informative
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-client-autoconfig/src/main/java/org/springframework/cloud/kubernetes/client/KubernetesClientUtils.java#L40

**Comment by chrismontone** [comment]
Spring Boot Version 2.7.5
Spring Cloud Kubernetes Version 2.1.5
-
On your default profile when running locally in an IDE if you turn off `cloud.kubernetes.enabled=false` in bootstramp.yaml, i.e:

```
  cloud:
    kubernetes:
      config:
        enabled: false
      enabled: false
```

I no longer get the `java.lang.NumberFormatException: null` error
