### ISSUE TITLE
Treat blank leader name as missing leader id

### ISSUE THREAD

**Issue by henrik242** [spring-cloud/spring-cloud-kubernetes#1037]
I had an issue where my `leader.id` was blank (because of manual configmap creation):
```{
    "apiVersion": "v1",
    "data": {
        "leader.id.my_app": ""
    },
    "kind": "ConfigMap",
```
This resulted in failing leader election:
```
java.lang.IllegalArgumentException: Name must be provided.
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withName(BaseOperation.java:239)
at io.fabric8.kubernetes.client.dsl.base.BaseOperation.withName(BaseOperation.java:91)
at org.springframework.cloud.kubernetes.fabric8.leader.Fabric8LeadershipController.isPodReady(Fabric8LeadershipController.java:131)
at org.springframework.cloud.kubernetes.fabric8.leader.Fabric8LeadershipController.update(Fabric8LeadershipController.java:56)
at org.springframework.cloud.kubernetes.fabric8.leader.Fabric8LeaderRecordWatcher.eventReceived(Fabric8LeaderRecordWatcher.java:84)
at org.springframework.cloud.kubernetes.fabric8.leader.Fabric8LeaderRecordWatcher.eventReceived(Fabric8LeaderRecordWatcher.java:32)
at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.eventReceived(AbstractWatchManager.java:186)
at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:242)
at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:93)
```
 Could this instance be treated as a missing `leader.id` instead, so that a new one can be inserted?

Thanks.

**Comment by henrik242** [comment]
Thanks!
