### ISSUE TITLE
After upgrade to 2.1.4 not Kubernetes context doesn't load

### ISSUE THREAD

**Issue by rechandler12** [spring-cloud/spring-cloud-kubernetes#1089]
**Describe the bug**
After upgrade to 2.1.4 when I run tests not in kubernetes i've got:
```
2022-09-26 12:32:39.480  INFO [jwt-generator,,] 3946211 --- [           main] o.s.c.k.client.KubernetesClientUtils     : Could not create the Kubernetes ApiClient in a cluster environment, because : 

java.lang.IllegalStateException: java.lang.NumberFormatException: Cannot parse null string
	at io.kubernetes.client.util.ClientBuilder.setBasePath(ClientBuilder.java:262)
	at io.kubernetes.client.util.ClientBuilder.cluster(ClientBuilder.java:248)
	at org.springframework.cloud.kubernetes.client.KubernetesClientUtils.kubernetesApiClient(KubernetesClientUtils.java:43)
```

This is because KubernetesClientAutoConfiguration#apiClient is load before KubernetesInformerAutoConfiguration#defaultApiClient

**Comment by wind57** [comment]
That is an info log - saying that it can not connect to a _clustered_ environment, so its going to fall-back to a _local_ env.

**Comment by rechandler12** [comment]
It is critical, later i've got:
```
2022-09-26 12:33:10.451 ERROR [jwt-generator,,] 3948242 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.cloud.kubernetes.commons.config.NamespaceResolutionFailedException: unresolved namespace
	at org.springframework.cloud.kubernetes.client.config.KubernetesClientConfigUtils.getApplicationNamespace(KubernetesClientConfigUtils.java:110)
	at org.springframework.cloud.kubernetes.client.config.KubernetesClientConfigMapPropertySourceLocator.getMapPropertySource(KubernetesClientConfigMapPropertySourceLocator.java:87)
	at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.getMapPropertySourceForSingleConfigMap(ConfigMapPropertySourceLocator.java:95)
	at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.lambda$locate$0(ConfigMapPropertySourceLocator.java:75)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
```

**Comment by wind57** [comment]
that is a different issue than the one you reported initially, see [here](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#namespace-resolution)

**Comment by rechandler12** [comment]
Sorry but I definitely disagree. My app when I run integration tests is not in kubernetes environment so it should not resolve any namespaces. You have even in logs:
Not running inside kubernetes. Skipping 'kubernetes' profile activation.
And as I stated before in previous version I have no issue with app.

**Comment by wind57** [comment]
this is an interesting ping-pong with various issues and a side-effect that you are currently seeing. 

Initially, we added a check for the namespace resolution (we need to do that, yes). 
Then we agreed that this is indeed a small problem and that users running things outside k8s should not get the exception you are seeing, so [we fixed it](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/883).

Then there were people [on the opposite side](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1038), so we kind of unfixed the fix. 

Since all the main changes now go to the `main` branch (which is != `2.1.x` releases), you will need to work around this problem, by setting explicitly: `spring.cloud.kubernetes.enabled=false`. You can do this via an environment variable too.

**Comment by wind57** [comment]
I just want to add that in `main`, this will work automatically, without any additional settings, because we rely there on `@ConditinalOnCloudPlatform`.

**Comment by leovx** [comment]
Hi @wind57, I have also encountered this issue recently. I would agree with @rechandler12 that the very fix is still required here for such detection. Since Spring Cloud is based on Spring Boot, using `@ConditionalOnCloudPlatform` is a much more elegant and intelligent way of solving the problems. Moreover, aligning it with new `3.x.x` is a wiser choice, coz eventually asking people to add some properties and then removing them after another upgrade does not make any sense. Making such happen in the way that is automatic and user-agnostic would be a better design.

**Comment by wind57** [comment]
@leovx first of all, I am terribly sorry for this, this is my fault. This is what happens when you try to make things better, occasionally things will break, as it did here. 

`@ConditionalOnCloudPlatform` should have not been part of the initial fix at all, we can't add it in only a few places, that's why I removed it and that is why it is part of `3.x.x` where we use it everywhere. 

As to setting that property as a workaround, you will not have to remove it when you do to `3.x.x` because we do not use it all, so it can stay there as it will have no impact.

**Comment by ilopezv** [comment]
Same probleme here.
It seems that in 2.1.4 version the kubernetes profile is loaded in local junit test and it produces the error mencioned above, in the other hand in version 2.1.3 all works well
In my personal case, the property spring.cloud.kubernetes.enabled=false is getting ignorded if it is defined in application-test.yaml but it works well if it is provided as enviroment_variable.

**Comment by wind57** [comment]
@ilopezv it should go in bootstrap.yaml.

**Comment by ilopezv** [comment]
@wind57 , bootstrap.yaml was deprecated in SB 2.4.
All things works fine in SB 2.7.4 + spring-cloud-kubernetes 2.1.3 combination and configuring it only with application.yaml & application-test.yaml

**Comment by wind57** [comment]
Deprecated, not removed.

And yes, I know it works in 2.1.3, because there we rely on `@ConditionalOnCloudPlatform`. Anyway, it will work either way if you set an env variable.

**Comment by leovx** [comment]
@wind57 Will 2.1.4 be the last version of it before we actually have 3.0.0? Any plan for the 3.0.0? Is 3.x.x Only for Spring Boot 3? If 2.1.4 will not the last version, shall we have `@ ConditionalOnCloudPlatform` everywhere for the next release, say 2.1.5 please? Understand that we can leave the very property for 3.x.x, but we already end up having too many. LOL.

**Comment by leovx** [comment]
> bootstrap.yam

@ilopezv Well, I believe you can simply have below in your pom.xml to have bootstrap.yaml work
`<dependency>`
`    <groupId>org.springframework.cloud</groupId>`
`    <artifactId>spring-cloud-starter-bootstrap</artifactId>`
`</dependency>`

**Comment by leovx** [comment]
@wind57  Hey Erabii, understand and thanks for the information.

**Comment by ryanjbaxter** [comment]
@leovx @rechandler12 @Jijii

When I place `spring.cloud.kubernetes.config.enabled=false` in `bootstrap.properties` the `PropertySourceLocator` is not loaded and you no longer see `NamespaceResolutionFailedException`.  Is that not your experience?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by leovx** [comment]
> @leovx @rechandler12 @Jijii
> 
> When I place `spring.cloud.kubernetes.config.enabled=false` in `bootstrap.properties` the `PropertySourceLocator` is not loaded and you no longer see `NamespaceResolutionFailedException`. Is that not your experience?

Hi @ryanjbaxter, I just got a chance to check your problem. Would you please provide a quick demo for the case you described? I added `PropertySourceLocator` with `spring.cloud.kubernetes.config.enabled: false` in my `bootstrap.yml` and the `locate()` method is actually triggered and running fine in my local non-kubernetes environment, with Spring Boot 2.7.5 and Spring Cloud 2021.0.4. I would suggest to check [this document](https://cloud.spring.io/spring-cloud-commons/multi/multi__spring_cloud_context_application_context_services.html#customizing-bootstrap-property-sources), and see if you have got your `PropertySourceLocator` properly registered in `spring.factories`.

**Comment by ryanjbaxter** [comment]
@wind57 is correct we cannot make such a change in a minor release

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
