### ISSUE TITLE
LoadBalancer for Kubernetes resulting in high number of requests to K8s API Server prior to every downstream call to lookup

### ISSUE THREAD

**Issue by dhananjay12** [spring-cloud/spring-cloud-kubernetes#1225]
**Describe the bug**
We have both Eureka discovery client (default) and spring-cloud-k8s  discovery client (**Fabric8** impl) in our spring apps that gets enabled based on environment. 

To make the switch from Eureka to K8s discovery we have following properties injected to all:
```
        - name: eureka.client.enabled
          value: "false"
        - name: spring.cloud.kubernetes.enabled
          value: "true"
        - name: spring.cloud.kubernetes.loadbalancer.mode
          value: "SERVICE"
```
When communicating from one service to another via LoadBalanced RestTemplate K8s API server is hit every time. This leads high load on K8s API resulting in rate limiting/blocking for the overall cluster.

 `spring.cloud.kubernetes.loadbalancer.mode` default to `POD` in which case its fine (K8s API server is not hit on each request ) but we wanted to "SERVICE" for our specific use case. 

A workaround is to disable loadbalancer in general when relying on K8s-Service using `spring.cloud.kubernetes.loadbalancer.enabled=false`, but this raises the question of usage of `loadbalancer.mode` other values.

Any insights on expected behaviour?

Versions - Happens both in spring-boot-3.0.2/spring-cloud-2022.0.1 and spring-boot-2.7.7/spring-cloud-2021.0.5

**Sample**
Sample code and process to reproduce locally has been pushed [here](https://github.com/dhananjay12/spring-microservice-demo/tree/master/k8s/spring-k8s-loadbalancer-test). The services involved in the sample K8s file source code is in the same repository.

**Comment by ryanjbaxter** [comment]
> A workaround is to disable loadbalancer in general when relying on K8s-Service using spring.cloud.kubernetes.loadbalancer.enabled=false, but this raises the question of usage of loadbalancer.mode other values.

What do you mean by this?  The only other option is POD.

**Comment by dhananjay12** [comment]
Sorry, yes the other option is just POD and with that, the K8s-api-server is not hit with every hop requestm while for SERVICE it does.

**Comment by ryanjbaxter** [comment]
So my thought is that when you specify `POD` that the default `ServiceInstanceSupplier` is used (which is based on whatever `DiscoveryClient` implementation is on the classpath is used).  In this case we will using caching by default
https://github.com/spring-cloud/spring-cloud-commons/blob/main/spring-cloud-loadbalancer/src/main/java/org/springframework/cloud/loadbalancer/annotation/LoadBalancerClientConfiguration.java#L158

Could you try creating a bean like this and see if it helps?

```
public ServiceInstanceListSupplier kubernetesClientServiceInstanceListSupplier(ConfigurableApplicationContext context, Environment environment, CoreV1Api coreV1Api,
			KubernetesClientServiceInstanceMapper mapper, KubernetesDiscoveryProperties discoveryProperties,
			KubernetesNamespaceProvider kubernetesNamespaceProvider) {
			return ServiceInstanceListSupplier.builder().withBase(new KubernetesClientServicesListSupplier(environment, mapper, discoveryProperties, coreV1Api,
				kubernetesNamespaceProvider))
					.withCaching().build(context);
		}
```

**Comment by dhananjay12** [comment]
Thanks for the response. We are using Fabric8 implementation. Is there a equivalent way there for the same bean? I see [this](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/ec9ecb28185d56ed9a4b41e89fd574fa2e978739/spring-cloud-kubernetes-fabric8-loadbalancer/src/main/java/org/springframework/cloud/kubernetes/fabric8/loadbalancer/Fabric8ServicesListSupplier.java#L43) but the constructor is not public.

**Comment by ryanjbaxter** [comment]
Ugh yeah that wont work.  Can you just copy the class into your project and try it that way?  We can make it public.

**Comment by dhananjay12** [comment]
I copied the class created the bean like
```
@Bean
	public ServiceInstanceListSupplier fabric8ServicesListSupplier(
			Environment environment, KubernetesClient kubernetesClient, Fabric8ServiceInstanceMapper mapper,
			KubernetesDiscoveryProperties discoveryProperties,
			ConfigurableApplicationContext context) {
		return ServiceInstanceListSupplier.builder().withBase(new Fabric8ServicesListSupplier(
						environment, kubernetesClient, mapper, discoveryProperties))
				.withCaching().build(context);
	}
```
On startup I get the following error:
```
2023-02-22T19:20:41.278Z ERROR 1 --- [           main[] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fabric8ServicesListSupplier' defined in com.mynotes.microservices.demo.serviceone.ServiceOneApplication: Failed to instantiate [org.springframework.cloud.loadbalancer.core.ServiceInstanceListSupplier[]: Factory method 'fabric8ServicesListSupplier' threw exception with message: Name must be provided.
    at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657) ~[spring-beans-6.0.4.jar:6.0.4[]
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:645) ~[spring-beans-6.0.4.jar:6.0.4[]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1324) ~[spring-beans-6.0.4.jar:6.0.4[]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1161) ~[spring-beans-6.0.4.jar:6.0.4[]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.0.4.jar:6.0.4[]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.4.jar:6.0.4[]
    at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.4.jar:6.0.4[]
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.4.jar:6.0.4[]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.4.jar:6.0.4[]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4[]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring-beans-6.0.4.jar:6.0.4[]
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[spring-context-6.0.4.jar:6.0.4[]
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.4.jar:6.0.4[]
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.2.jar:3.0.2[]
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.2.jar:3.0.2[]
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.2.jar:3.0.2[]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.2.jar:3.0.2[]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.2.jar:3.0.2[]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.2.jar:3.0.2[]
    at com.mynotes.microservices.demo.serviceone.ServiceOneApplication.main(ServiceOneApplication.java:34) ~[classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.loadbalancer.core.ServiceInstanceListSupplier[]: Factory method 'fabric8ServicesListSupplier' threw exception with message: Name must be provided.
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.4.jar:6.0.4[]
    at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-6.0.4.jar:6.0.4[]
    ... 19 common frames omitted
Caused by: java.lang.IllegalArgumentException: Name must be provided.
    at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.withName(BaseOperation.java:219) ~[kubernetes-client-6.2.0.jar:na[]
    at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.withName(BaseOperation.java:88) ~[kubernetes-client-6.2.0.jar:na[]
```
Anything I am missing?

**Comment by ryanjbaxter** [comment]
Is there more to that stacktrace that is cut off?

**Comment by dhananjay12** [comment]
Sorry few lines got trimmed. Updated the above comment

**Comment by ryanjbaxter** [comment]
Try setting `loadbalancer.client.name` to the name of the service you want to load balance.

**Comment by dhananjay12** [comment]
After setting `loadbalancer.client.name` the service did start without any error but while hitthig the hop request I was getting this error:
```
2023-02-23T18:17:57.244Z ERROR 1 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw excepti │
│ org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.loadbalancer.core.ServiceInstanceListSupplier' available: expect │
│     at org.springframework.beans.factory.config.DependencyDescriptor.resolveNotUnique(DependencyDescriptor.java:218) ~[spring-beans-6.0.4.jar:6.0.4]                                      │
│     at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1383) ~[spring-beans-6.0.4.jar:6.0.4] 
```
Making the bean `@Primary` and the service was routing correctly without continuous hit K8s-api-server. 
To sum up the changes:
1) Copied `Fabric8ServicesListSupplier` class to the local project  (because the constructor has default acess)
2) Created the ServiceInstanceListSupplier bean
```
    @Bean
	@Primary
    public ServiceInstanceListSupplier fabric8ServicesListSupplier(
            Environment environment, KubernetesClient kubernetesClient, Fabric8ServiceInstanceMapper mapper,
            KubernetesDiscoveryProperties discoveryProperties,
            ConfigurableApplicationContext context) {
        return ServiceInstanceListSupplier.builder().withBase(new Fabric8ServicesListSupplier(
                        environment, kubernetesClient, mapper, discoveryProperties))
                .withCaching().build(context);
    }
```
3) In service-one deployment, had to hardcode the service-two name
```
        - name: loadbalancer.client.name
          value: "service-two"
```
Thanks for the insight. 
I guess the next followup would be:
1) Will there be any changes made in `spring-cloud-kubernetes` `Fabric8` implementation to accommodate this (the class constructor and `loadbalancer.client.name` to be dynamically registered)?
2) If `spring.cloud.kubernetes.loadbalancer.mode` is `SERVICE`, does client side loadbalancing makes sense as the K8s-Service will actually loadbalance to the registered pods? Or this would come into picture when the same service is registered in different namespace/zones (havent tested this scenario, for now we have all things in the same namespace)
