### ISSUE TITLE
Kubernetes errors prevent application from starting outside of kubernetes

### ISSUE THREAD

**Issue by abickerton** [spring-cloud/spring-cloud-kubernetes#1365]
**Describe the bug**
There appears to be a problem with the kubernetes profile autoconfiguration, Spring-cloud-kubernetes code is getting initialised when not in a pod. 

spring-cloud-dependencies : 2021.0.6
spring-cloud-kubernetes-dependencies : 2.1.6
spring-cloud-starter-kubernetes-client-all : 2.1.6
spring-cloud-starter-kubernetes-client-config: 2.1.6

**Sample**
- Create a hello world app using spring initializer https://start.spring.io/
- Java 11
- Add the above dependencies
- Start the application as a jar file. java -jar [project.jar]
The following error is shown.NamespaceResolutionFailedException: unresolved namespace

```
2023-06-13 15:46:15.953  WARN 401322 --- [           main] ubernetesProfileEnvironmentPostProcessor : Not running inside kubernetes. Skipping 'kubernetes' profile activation.
2023-06-13 15:46:16.348  INFO 401322 --- [           main] o.s.c.k.client.KubernetesClientUtils     : Could not create the Kubernetes ApiClient in a cluster environment, because : 

java.lang.IllegalStateException: java.lang.NumberFormatException: null
	at io.kubernetes.client.util.ClientBuilder.setBasePath(ClientBuilder.java:262) ~[client-java-13.0.2.jar:na]
	at io.kubernetes.client.util.ClientBuilder.cluster(ClientBuilder.java:248) ~[client-java-13.0.2.jar:na]
	at org.springframework.cloud.kubernetes.client.KubernetesClientUtils.kubernetesApiClient(KubernetesClientUtils.java:43) ~[spring-cloud-kubernetes-client-autoconfig-2.1.6.jar:2.1.6]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration.apiClient(KubernetesClientAutoConfiguration.java:45) ~[spring-cloud-kubernetes-client-autoconfig-2.1.6.jar:2.1.6]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$f825df85.CGLIB$apiClient$0(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.1.6.jar:2.1.6]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$f825df85$$FastClassBySpringCGLIB$$9a790652.invoke(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.1.6.jar:2.1.6]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.26.jar:5.3.26]

** OMITTED**


 :: Spring Boot ::               (v2.7.10)
2023-06-13 15:13:59.756 ERROR 264289 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.cloud.kubernetes.commons.config.NamespaceResolutionFailedException: unresolved namespace
	at org.springframework.cloud.kubernetes.client.config.KubernetesClientConfigUtils.getApplicationNamespace(KubernetesClientConfigUtils.java:110) ~[spring-cloud-kubernetes-client-config-2.1.6.jar:2.1.6]
	at org.springframework.cloud.kubernetes.client.config.KubernetesClientConfigMapPropertySourceLocator.getMapPropertySource(KubernetesClientConfigMapPropertySourceLocator.java:87) ~[spring-cloud-kubernetes-client-config-2.1.6.jar:2.1.6]
	at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.getMapPropertySourceForSingleConfigMap(ConfigMapPropertySourceLocator.java:95) ~[spring-cloud-kubernetes-commons-2.1.6.jar:2.1.6]
	at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.lambda$locate$0(ConfigMapPropertySourceLocator.java:75) ~[spring-cloud-kubernetes-commons-2.1.6.jar:2.1.6]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.locate(ConfigMapPropertySourceLocator.java:75) ~[spring-cloud-kubernetes-commons-2.1.6.jar:2.1.6]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51) ~[spring-cloud-context-3.1.6.jar:3.1.6]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47) ~[spring-cloud-context-3.1.6.jar:3.1.6]
	at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.locateCollection(ConfigMapPropertySourceLocator.java:87) ~[spring-cloud-kubernetes-commons-2.1.6.jar:2.1.6]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95) ~[spring-cloud-context-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:604) ~[spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) ~[spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306) ~[spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.10.jar:2.7.10]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.10.jar:2.7.10]
```

**Workaround**
Both of these should not be necessary

1: 
Define the property
spring.cloud.kubernetes.enabled=false and in your tests add @SpringBootTest(properties = "spring.cloud.kubernetes.enabled=false") 

2:
Add a bootstrap.yml file containing the following,

```
spring:
  cloud:
    compatibility-verifier.enabled: false
    kubernetes:
      enabled: false
      reload.enabled: false
      discovery.enabled: false
```

**Comment by ryanjbaxter** [comment]
The other option is to define `spring.cloud.kubernetes.client.namespace` in bootstrap.properties.  

In 2022.0.x we don't have this problem because all things Kubernetes is disabled automatically based on the `spring.main.cloud-platform` property not being `kubernetes`.  In 2021.0.x we don't have that in order to maintain backward compatibility.  You have to manually disable Spring Cloud Kuberentes.

**Comment by abickerton** [comment]
So updating to 2022.0.x would remove the need for either of the workarounds?
I can't use anything after Java 11 due to other factors, Is it still Java 11 compatible?
