### ISSUE TITLE
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified:     

### ISSUE THREAD

**Issue by ahsimon** [spring-cloud/spring-cloud-kubernetes#137]
trying to reading configMap from a BluemixCluster the following error is thows,  if default certificate is created by cloud provider, how can we pass through   this kind of  exception ?

: 2017-10-16 20:04:35,391 [main] DEBUG o.s.c.e.PropertySourcesPropertyResolver - Could not find key 'context.initializer.classes' in any property source
2017-10-16 20:04:35,467 [main] WARN  i.f.s.c.kubernetes.StandardPodUtils - Failed to get pod with name:[xxx-1720588040-757j4]. You should look into this if things aren't working as you expect. Are you missing serviceaccount permissions?
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:61)
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:52)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:199)
        at io.fabric8.spring.cloud.kubernetes.StandardPodUtils.internalGetPod(StandardPodUtils.java:56)
        at io.fabric8.spring.cloud.kubernetes.StandardPodUtils.lambda$new$0(StandardPodUtils.java:40)
        at io.fabric8.spring.cloud.kubernetes.LazilyInstantiate.swapper(LazilyInstantiate.java:41)
        at io.fabric8.spring.cloud.kubernetes.LazilyInstantiate.lambda$new$0(LazilyInstantiate.java:34)
        at io.fabric8.spring.cloud.kubernetes.LazilyInstantiate.get(LazilyInstantiate.java:29)
        at io.fabric8.spring.cloud.kubernetes.profile.KubernetesProfileApplicationListener.addKubernetesProfile(KubernetesProfileApplicationListener.java:49)
        at io.fabric8.spring.cloud.kubernetes.profile.KubernetesApplicationContextInitializer.initialize(KubernetesApplicationContextInitializer.java:53)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:636)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:350)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1187)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176)
        at cl.tchile.ms.buzon.ms.app.GetAllApp.startMicroservice(GetAllApp.java:99)
        at cl.tchile.ms.buzon.ms.app.GetAllApp.main(GetAllApp.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified:
    certificate: sha256/MhB5QeflIBAZW+YgfocFbtSDVr/i2dSptqIXi2r1TXY=
    DN: CN=172.21.0.1
    subjectAltNames: [172.21.0.1, 10.76.103.228, 184.173.44.62]
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:308)

**Comment by osoriano** [comment]
If you're not able to update the certs to include kubernetes.default.svc, there is a workaround discussed in https://github.com/fabric8io/fabric8/issues/6229#issuecomment-247373967

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.
