### ISSUE TITLE
Unset endpointslices causes NPE on all the services

### ISSUE THREAD

**Issue by SabareeshGC** [spring-cloud/spring-cloud-kubernetes#1413]
**Describe the bug**
When there is an unset endpoint slice such as this one below it causes all the services to throw npe when getting endpoint slices 

```
kubectl get endpointslices
springadmin-48mr7                     IPv4          <unset>          <unset>                                                 59d
```

```


  | Error watching Kubernetes Services
-- | --


	
java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at org.springframework.cloud.kubernetes.fabric8.discovery.Fabric8CatalogWatchContext.state(Fabric8CatalogWatchContext.java:42)
	at org.springframework.cloud.kubernetes.fabric8.discovery.Fabric8EndpointSliceV1CatalogWatch.apply(Fabric8EndpointSliceV1CatalogWatch.java:72)
	at org.springframework.cloud.kubernetes.fabric8.discovery.Fabric8EndpointSliceV1CatalogWatch.apply(Fabric8EndpointSliceV1CatalogWatch.java:39)
	at org.springframework.cloud.kubernetes.fabric8.discovery.KubernetesCatalogWatch.catalogServicesWatch(KubernetesCatalogWatch.java:73)
	at jdk.internal.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SabareeshGC** [comment]
This happened on the production cluster so i had to terminate the zombie endpoint slice. There is a possibility this happened when we renamed the service,deployment from springadmin to spring-admin so now had both of the slices but this happened while ago but it was more visible when we turned the flag on to use endpoint slice instead of endpoint.

**Comment by SabareeshGC** [comment]
All you need to do is get endpoint slice in your namespace to unset and just start a service with spring cloud kuberentes fabrica8 discovery client with endpoint slices flag turned on

**Comment by SabareeshGC** [comment]
Well as you know we dont know exact reproduce steps to get in that state but we use helm. I tried few things and this seems to work , please apply following to create a new endpoint slice which will be created as unset 

```
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints: null
kind: EndpointSlice
metadata:
  annotations:
   generateName: test-unset-endpoint-slice
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: test-unset-endpoint-slice
    kubernetes.io/service-name: test-unset-endpoint-slice
  name: test-unset-endpoint-slice
  namespace: default
ports: null
```
