### ISSUE TITLE
discoveryserver: readiness probe shouldn't pass when permissions are incorrect

### ISSUE THREAD

**Issue by codefromthecrypt** [spring-cloud/spring-cloud-kubernetes#1583]
**Describe the bug**

something like https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1580 should be detected by a readiness probe, but it wasn't.

subject to opinion, but I think one of ready or health or both should fail if permissions are wrong, as otherwise you need to look at logs to notice something is amok.

**Sample**

I used a [helm chart](https://github.com/codecentric/spring-boot-admin-runtime-playground/tree/main/kubernetes/helm-charts/spring-cloud-kubernetes-discoveryserver) by @andreasfritz which also doesn't add the required permission, yet the readiness probe seems to pass (correct if wrong)

**Comment by codefromthecrypt** [comment]
ps the following helm test passes despite errors in the logs

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "spring-cloud-kubernetes-discoveryserver.fullname" . }}-test-connection"
  labels:
    {{- include "spring-cloud-kubernetes-discoveryserver.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget', '-qO', '-']. # for debug print the whole response to console
      args: ['{{ include "spring-cloud-kubernetes-discoveryserver.fullname" . }}:{{ .Values.service.port }}/apps']
  restartPolicy: Never
```

again https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1580 fixed this, but there should have been something that failed and maybe folks closer to the project can figure a fail-fast!
```
2024-02-21T09:14:35.056Z  WARN 1 --- [           main] o.s.c.k.client.KubernetesClientPodUtils  : error reading pod, with error : {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"spring-cloud-kubernetes-discoveryserver-8b8f89db5-zfnpd\" is forbidden: User \"system:serviceaccount:default:spring-cloud-kubernetes-discoveryserver\" cannot get resource \"pods\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"name":"spring-cloud-kubernetes-discoveryserver-8b8f89db5-zfnpd","kind":"pods"},"code":403}

2024-02-21T09:14:35.057Z  WARN 1 --- [           main] o.s.c.k.client.KubernetesClientPodUtils  : Failed to get pod with name:[spring-cloud-kubernetes-discoveryserver-8b8f89db5-zfnpd]. You should look into this if things aren't working as you expect. Are you missing serviceaccount permissions?

io.kubernetes.client.openapi.ApiException: 
        at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:989) ~[client-java-api-19.0.0.jar:na]
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:905) ~[client-java-api-19.0.0.jar:na]
        at io.kubernetes.client.openapi.apis.CoreV1Api.readNamespacedPodWithHttpInfo(CoreV1Api.java:26769) ~[client-java-api-19.0.0.jar:na]
        at io.kubernetes.client.openapi.apis.CoreV1Api.readNamespacedPod(CoreV1Api.java:26747) ~[client-java-api-19.0.0.jar:na]
        at org.springframework.cloud.kubernetes.client.KubernetesClientPodUtils.internalGetPod(KubernetesClientPodUtils.java:87) ~[spring-cloud-kubernetes-client-autoconfig-3.1.0.jar:3.1.0]
        at org.springframework.cloud.kubernetes.commons.LazilyInstantiate.get(LazilyInstantiate.java:47) ~[spring-cloud-kubernetes-commons-3.1.0.jar:3.1.0]
        at org.springframework.cloud.kubernetes.client.KubernetesClientPodUtils.isInsideKubernetes(KubernetesClientPodUtils.java:80) ~[spring-cloud-kubernetes-client-autoconfig-3.1.0.jar:3.1.0]
        at org.springframework.cloud.kubernetes.commons.discovery.KubernetesDiscoveryClientHealthIndicatorInitializer.postConstruct(KubernetesDiscoveryClientHealthIndicatorInitializer.java:49) ~[spring-cloud-kubernetes-commons-3.1.0.jar:3.1.0]
```

**Comment by codefromthecrypt** [comment]
so I looked into this and basically the API doesn't use this pod data. It is grabbed just in case there is a consumer of `RegisteredEventSource`.

What fails and makes the large error should be reconsidered. For example, if this binary has no consumers of the data, don't ask for the pod (and avoid the permissions or scary error if they aren't there). This seems better from both an experience and a security pov.

cc @iocanel not because you intended this, but because some old version of a file in question has your author tag ;) p.s. hi again!

```
	@PostConstruct
	private void postConstruct() {
		LOG.debug(() -> "publishing InstanceRegisteredEvent");
		InstanceRegisteredEvent<RegisteredEventSource> instanceRegisteredEvent = new InstanceRegisteredEvent<>(
				new RegisteredEventSource("kubernetes", podUtils.isInsideKubernetes(), podUtils.currentPod().get()),
				null);
		this.applicationEventPublisher.publishEvent(instanceRegisteredEvent);
	}
```

**Comment by ryanjbaxter** [comment]
So the issue is without the pod resource permissions when the instance registered event is fired we get the permissions issue?

**Comment by codefromthecrypt** [comment]
thanks for the analysis. I think there are a lot of projects who silently (like not log at WARN level) handle errors that don't affect functionality. If there's a way to make this error not visible I wouldn't notice. For now, the yaml adds the permission only needed to make this log warning go away. Any way to roll back that permission and also *by default* not have to do anything special to have a clean boot is positive!

**Comment by codefromthecrypt** [comment]
> So the issue is without the pod resource permissions when the instance registered event is fired we get the permissions issue?

yep exactly this. several stack traces, but the actual data isn't used.

**Comment by ryanjbaxter** [comment]
I guess I am curious as to why we would publish an instance registered event when starting the discovery server, something to look at.

anyways we should not be producing the error so I agree it’s something we should address

**Comment by codefromthecrypt** [comment]
> I guess I am curious as to why we would publish an instance registered event when starting the discovery server, something to look at.

I went down the rabbit hole on this, and there are consumes of this but only in tests. Maybe someone added it for a custom server 🤷

**Comment by codefromthecrypt** [comment]
another glitch you can see on this is that it is not using the bean for the api client, which means it isn't instrumented or configured. this leads to visibility gaps also. I really think this should be disabled by default as the benefit is too small. Something else can enable it and accept the problems it has. 

my 2p

**Comment by codefromthecrypt** [comment]
@wind57 I happened upon this type `K8sPodLabelsAndAnnotationsSupplier` which appears to read pod apis. I haven't traced it yet, but maybe this ends up requiring pod perms, too?
