### ISSUE TITLE
difficulty running Fabric8IstioIT locally

### ISSUE THREAD

**Issue by codefromthecrypt** [spring-cloud/spring-cloud-kubernetes#1602]
**Describe the bug**
I can see that `Fabric8IstioIT` runs in the workflow, but I'm having trouble executing it locally. First, I have to disable ryuk, then it still doesn't work on account of some resources. Are there some instructions I may be missing? I run install first. Note: I am running an M2 macbook (aarch64) and using colima.

**Sample**

ryuk enabled (default)
```
[INFO] Running org.springframework.cloud.kubernetes.fabric8.client.istio.Fabric8IstioIT
13:12:18.044 [main] INFO  org.testcontainers.images.PullPolicy - Image pull policy will be performed by: DefaultPullPolicy()
13:12:18.048 [main] INFO  org.testcontainers.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
13:12:18.264 [main] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///Users/adrian/.colima/default/docker.sock
13:12:18.267 [main] INFO  org.testcontainers.DockerClientFactory - Docker host IP address is 192.168.106.2
13:12:18.278 [main] INFO  org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 24.0.9
  API Version: 1.43
  Operating System: Ubuntu 23.10
  Total Memory: 7922 MB
13:12:18.282 [main] INFO  org.testcontainers.DockerClientFactory - Checking the system...
13:12:18.282 [main] INFO  org.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
13:12:18.302 [main] INFO  tc.rancher/k3s:v1.25.4-k3s1 - Creating container for image: rancher/k3s:v1.25.4-k3s1
13:12:18.349 [main] INFO  org.testcontainers.utility.RegistryAuthLocator - Credential helper/store (docker-credential-osxkeychain) does not have credentials for https://index.docker.io/v1/
13:12:18.352 [main] INFO  tc.testcontainers/ryuk:0.6.0 - Creating container for image: testcontainers/ryuk:0.6.0
13:12:18.407 [main] INFO  tc.testcontainers/ryuk:0.6.0 - Container testcontainers/ryuk:0.6.0 is starting: f55a49f5bd6f328e0709ce8155b559c9a763563487be704527956ed724036f19
13:12:18.629 [main] INFO  tc.testcontainers/ryuk:0.6.0 - Container testcontainers/ryuk:0.6.0 started in PT0.276852S
13:12:18.642 [testcontainers-ryuk] WARN  org.testcontainers.utility.RyukResourceReaper - Can not connect to Ryuk at 192.168.106.2:32773
java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:757)
	at org.testcontainers.utility.RyukResourceReaper.lambda$null$1(RyukResourceReaper.java:105)
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$2(RyukResourceReaper.java:101)
	at java.base/java.lang.Thread.run(Thread.java:1583)
13:12:18.910 [testcontainers-ryuk] WARN  org.testcontainers.utility.RyukResourceReaper - Can not connect to Ryuk at 192.168.106.2:32773
```

ryuk disabled
```
[INFO] Running org.springframework.cloud.kubernetes.fabric8.client.istio.Fabric8IstioIT
13:16:28.644 [main] INFO  org.testcontainers.images.PullPolicy - Image pull policy will be performed by: DefaultPullPolicy()
13:16:28.646 [main] INFO  org.testcontainers.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
13:16:28.853 [main] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///Users/adrian/.colima/default/docker.sock
13:16:28.854 [main] INFO  org.testcontainers.DockerClientFactory - Docker host IP address is null
13:16:28.863 [main] INFO  org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 24.0.9
  API Version: 1.43
  Operating System: Ubuntu 23.10
  Total Memory: 7922 MB
13:16:28.863 [main] WARN  org.testcontainers.utility.ResourceReaper - 
********************************************************************************
Ryuk has been disabled. This can cause unexpected behavior in your environment.
********************************************************************************
13:16:28.865 [main] INFO  org.testcontainers.DockerClientFactory - Checking the system...
13:16:28.865 [main] INFO  org.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
13:16:28.884 [main] INFO  tc.rancher/k3s:v1.25.4-k3s1 - Creating container for image: rancher/k3s:v1.25.4-k3s1
13:16:28.930 [main] INFO  org.testcontainers.utility.RegistryAuthLocator - Credential helper/store (docker-credential-osxkeychain) does not have credentials for https://index.docker.io/v1/
13:16:28.940 [main] INFO  tc.alpine:3.16 - Pulling docker image: alpine:3.16. Please be patient; this may take some time but only needs to be done once.
13:16:32.664 [docker-java-stream-1037873389] INFO  tc.alpine:3.16 - Starting to pull image
13:16:32.681 [docker-java-stream-1037873389] INFO  tc.alpine:3.16 - Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
13:16:35.335 [docker-java-stream-1037873389] INFO  tc.alpine:3.16 - Pulling image layers:  0 pending,  1 downloaded,  0 extracted, (2 MB/2 MB)
13:16:35.442 [docker-java-stream-1037873389] INFO  tc.alpine:3.16 - Pulling image layers:  0 pending,  1 downloaded,  1 extracted, (2 MB/2 MB)
13:16:35.450 [docker-java-stream-1037873389] INFO  tc.alpine:3.16 - Pull complete. 1 layers, pulled in 2s (downloaded 2 MB at 1 MB/s)
13:16:35.450 [main] INFO  tc.alpine:3.16 - Image alpine:3.16 pull took PT6.510444S
13:16:36.941 [main] INFO  tc.rancher/k3s:v1.25.4-k3s1 - Container rancher/k3s:v1.25.4-k3s1 is starting: 2c4d57bd83fdb42c2112dcd3d726c8609c840546fa0b98a65ecacb88814e720a
13:16:55.749 [main] INFO  tc.rancher/k3s:v1.25.4-k3s1 - Container rancher/k3s:v1.25.4-k3s1 started in PT26.865397S
13:17:01.057 [awaitility-thread] INFO  org.springframework.cloud.kubernetes.integration.tests.commons.Commons - error is : ctr: open /var/folders/vd/1cf8zdb1721f4z5rjggy8bp40000gn/T/spring-cloud-kubernetes-fabric8-client-istio.tar: no such file or directory
```

cc @wind57 as seems you have been able to get this working. ps I have already tried upgrading the docker and testcontainers drivers. PS the istio, alpine, etc versions in this test are very out of date.

**Comment by codefromthecrypt** [comment]
good point that k3s isn't as far behind as the others. nevermind that.

my machine is in process doing the dashaun thing, and hopefully we can stop this problem forever via https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1603 I keep forgetting this, but it really isn't something people should have to memorize.

will report back if things progress now.

**Comment by codefromthecrypt** [comment]
ps if only java 17 is supported, I would suggest adding maven-enforcer-plugin config, for a similar reason as adding a maven profile to fix the image. Basically, people shouldn't have to remember a lot of special rules. If we decide things don't work past 17, we ought to prevent it by default. Power users can always use a property to skip enforcer.

**Comment by codefromthecrypt** [comment]
ok so downgrading to JRE 17 and also rebuilding with dashaun, same error

```
16:26:29.032 [awaitility-thread] INFO  org.springframework.cloud.kubernetes.integration.tests.commons.Commons - error is : ctr: open /var/folders/vd/1cf8zdb1721f4z5rjggy8bp40000gn/T/spring-cloud-kubernetes-fabric8-client-istio.tar: no such file or directory
```

My guess indeed is this about colima as it is running in a VM, and the test may be assuming the image it is pulling outside docker is actually on the same host. It is may be possible to redo this so that it can pull the image from k3s node to avoid this problem. I won't run docker desktop as it is a licensed product and also colima is generally useful for other things. I'll just rename this to an enhancement request.

**Comment by codefromthecrypt** [comment]
fyi here's how I use colima

```bash
$ colima start --cpu 4 --memory 8 --network-address
```

Most of the time I also add ` --kubernetes` so that it will also start k3s by default, but anyway to reproduce, I do `colima delete` then recreate per above.

**Comment by codefromthecrypt** [comment]
The problem here is that the current code assumes the host running the testcontainers code is the same as the docker host. This is not true in colima (nor would be for a cloud host).

Here's a working version of image copying, but I ran into other problems so the whole IT isn't working, yet.

```java
	/**
	 * Container path corresponding to {@link #HOST_IMAGE_PATH}.
	 */
	public static final Path CONTAINER_IMAGE_PATH = Path.of("/images");

	private static final K3sContainer CONTAINER =
		new FixedPortsK3sContainer(DockerImageName.parse(Commons.RANCHER))
			.configureFixedPorts(EXPOSED_PORTS)
// here don't assume the path is the same, this helps keep things more sane later
			.withFileSystemBind(HOST_IMAGE_PATH.toFile().getAbsolutePath(),
				CONTAINER_IMAGE_PATH.toString(), BindMode.READ_WRITE)
			.withCommand(Commons.RANCHER_COMMAND);

--snip--

// different version of loadImage that doesn't assume the JVM's host is the same as the docker host
	public static void loadImage(String image, String tag, K3sContainer k3s)
		throws Exception {
		DockerClient client = k3s.getDockerClient();
		image = image + ":" + tag;
		String id = client.inspectImageCmd(image)
			.exec()
			.getId()
			.replace("sha256:", "");

		Path hostPath = HOST_IMAGE_PATH.resolve(id);
		if (!hostPath.toFile().exists()) {
			LOG.info("saving image " + image + " to " + hostPath);
			try (SaveImageCmd saveCmd = client.saveImageCmd(image);
				 InputStream in = saveCmd.exec();
				 OutputStream out = Files.newOutputStream(hostPath)) {
				in.transferTo(out);
			} catch (Exception ex) {
				hostPath.toFile().delete();
				throw ex;
			}
		}

		Path containerPath = CONTAINER_IMAGE_PATH.resolve(id);
		LOG.info("copying " + hostPath + " to " + containerPath);
		k3s.copyFileToContainer(MountableFile.forHostPath(hostPath), containerPath.toString());
		LOG.info("importing image " + image + " from " + containerPath);
		Container.ExecResult exec =
			k3s.execInContainer("ctr", "images", "import", containerPath.toString());
		if (exec.getExitCode() != 0) {
			throw new RuntimeException("Failed to load image " + image + ": " + exec);
		}
	}


```

**Comment by wind57** [comment]
this will be closed when : https://github.com/spring-cloud/spring-cloud-kubernetes/issues/2146 will. 

there is no need to do any work here, since we will drop this integration test in the next major release.

**Comment by UmeshJoshi13** [comment]
Replace the loadImage() method call with the existing load() method (lines 134-173 in Commons.java), which is more resilient as it:

1. First checks /tmp/docker/images for pre-built tars (useful in CI/CD)
2. Falls back to pulling the image directly inside K3s via ctr pull (containerd)
3. Avoids the problematic Docker save + ctr import sequence
4. Supports Docker Hub credentials via environment variables
5. Automatically handles OCI and multi-platform images

**Comment by wind57** [comment]
@UmeshJoshi13 this is obviously AI comments, at least for me. If you have read the comments here, it would have been no need for the latest comment at all. I don't know what is the policy in spring for such things
