### ISSUE TITLE
Importing kubernetes: config doesn't work as document with YAML config

### ISSUE THREAD

**Issue by nstuart-idexx** [spring-cloud/spring-cloud-kubernetes#1610]
When specifying `spring.config.import: "kubernetes:"`, the application fails to start with the following exception:

    java.lang.IllegalStateException: Unable to load config data from '"kubernetes:"'
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferences(StandardConfigDataLocationResolver.java:143)
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferences(StandardConfigDataLocationResolver.java:128)
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.resolve(StandardConfigDataLocationResolver.java:121)

If I change the import to: `spring.config.import: kubernetes://` it works as expected.

The quotes in the failing example are the documented way to escape the : character in YAML, and the kubernetes config docs only show the properties file format using `=`, and no `//` on the end of the value.

I would expect both formats to work. Worse case, the documentation should be updated to show the expected yaml format.

May be that this is a bug in the root ConfigDataResolvers logic?  I have not tried other types of imports to see if those also fail when escaped.

**Comment by nstuart-idexx** [comment]
I'll see what I can do, to be 100% accurate, my actual import line is:
   
    spring;
        config:
            import: vault://, "kubernetes:"

not sure it matters, but I'll see if I can reproduce in a smaller sample.

**Comment by nstuart-idexx** [comment]
Yep, that works, which makes sense thinking about how spring reads list properties. just wasn't terribly intuitive when I was staring at the error. I'll mark this as closed.
