### ISSUE TITLE
Problems running leader example

### ISSUE THREAD

**Issue by adilfulara** [spring-cloud/spring-cloud-kubernetes#249]
I tried to run the kubernetes-leader-election-example

```
➜  kubernetes-leader-election-example git:(master) kubectl get all
NAME                                        AGE
deploy/kubernetes-leader-election-example   10m

NAME                                              AGE
rs/kubernetes-leader-election-example-8779fccdb   10m

NAME                                                    READY     STATUS             RESTARTS   AGE
po/kubernetes-leader-election-example-8779fccdb-4hxjd   0/1       CrashLoopBackOff   6          10m

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
svc/kubernetes                           ClusterIP   10.96.0.1       <none>        443/TCP          54m
svc/kubernetes-leader-election-example   NodePort    10.103.60.251   <none>        8080:31541/TCP   10m
```
and saw following error in the log. how does one create the role and role binding mentioned in the readme.

```2018-10-10 05:55:36.084  WARN 1 --- [default.svc/...] i.f.k.c.d.i.WatchConnectionManager       : Exec Failure: HTTP 403, Status: 403 - configmaps is forbidden: User "system:serviceaccount:default:default" cannot watch configmaps in the namespace "default"

java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:216) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:183) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) [okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.8.1.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

2018-10-10 05:55:36.089  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'leaderInitiator'; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: configmaps is forbidden: User "system:serviceaccount:default:default" cannot watch configmaps in the namespace "default"
2018-10-10 05:55:36.090  INFO 1 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2018-10-10 05:55:36.101  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2018-10-10 05:55:36.102  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
Exception in thread "OkHttp Dispatcher" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1c366b10 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@77b43eb6[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.scheduleReconnect(WatchConnectionManager.java:302)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$800(WatchConnectionManager.java:49)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onFailure(WatchConnectionManager.java:209)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:543)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:185)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-10-10 05:55:36.146  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-10-10 05:55:36.149 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'leaderInitiator'; nested exception is io.fabric8.kubernetes.client.KubernetesClientException: configmaps is forbidden: User "system:serviceaccount:default:default" cannot watch configmaps in the namespace "default"
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.1.1.BUILD-SNAPSHOT.jar!/:5.1.1.BUILD-SNAPSHOT]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.1.1.BUILD-SNAPSHOT.jar!/:5.1.1.BUILD-SNAPSHOT]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.1.1.BUILD-SNAPSHOT.jar!/:5.1.1.BUILD-SNAPSHOT]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.1.1.BUILD-SNAPSHOT.jar!/:5.1.1.BUILD-SNAPSHOT]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.1.1.BUILD-SNAPSHOT.jar!/:5.1.1.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879) ~[spring-context-5.1.1.BUILD-SNAPSHOT.jar!/:5.1.1.BUILD-SNAPSHOT]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.1.0.BUILD-SNAPSHOT.jar!/:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.1.BUILD-SNAPSHOT.jar!/:5.1.1.BUILD-SNAPSHOT]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.0.BUILD-SNAPSHOT.jar!/:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771) [spring-boot-2.1.0.BUILD-SNAPSHOT.jar!/:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.1.0.BUILD-SNAPSHOT.jar!/:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.1.0.BUILD-SNAPSHOT.jar!/:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1256) [spring-boot-2.1.0.BUILD-SNAPSHOT.jar!/:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1244) [spring-boot-2.1.0.BUILD-SNAPSHOT.jar!/:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.kubernetes.examples.App.main(App.java:26) [classes!/:1.0.0.BUILD-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [kubernetes-leader-election-example-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [kubernetes-leader-election-example-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [kubernetes-leader-election-example-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [kubernetes-leader-election-example-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: configmaps is forbidden: User "system:serviceaccount:default:default" cannot watch configmaps in the namespace "default"
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onFailure(WatchConnectionManager.java:194) ~[kubernetes-client-3.1.10.jar!/:na]
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:543) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:185) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.8.1.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]```

**Comment by geoand** [comment]
This is a RBAC issue as can be seen here:

```
 io.fabric8.kubernetes.client.KubernetesClientException: configmaps is forbidden: User "system:serviceaccount:default:default" cannot watch configmaps in the namespace "default"
```

You need to make sure that the default user has the permissions to watch for configmap in the default namespace (or use another user that has these permissions).

**Comment by adilfulara** [comment]
@geoand could the docs be clarified as to what is needed. i am happy to submit a PR if i know what to execute.

**Comment by spencergibb** [comment]
Closing as answered.
