### ISSUE TITLE
KubernetesClientException when trying to start Java 11 + Spring Boot 2.1.0 service on OpenShift 3.9

### ISSUE THREAD

**Issue by gdubya** [spring-cloud/spring-cloud-kubernetes#274]
We have a slight variation of the same issue as in #216, except that the root cause is a broken pipe. We have already added the "cluster-reader" role to the service account. Is there any other role that should be applied? This is for an OpenShift 3.9 cluster (Kubernetes 1.9.1) FWIW. Oh, and the service is using Java 11... maybe that's related to the issue?

```
2018-11-23 11:28:54.408  WARN 1 --- [           main] o.s.cloud.kubernetes.StandardPodUtils    : Failed to get pod with name:[happiness-service-17-flxlj]. You should look into this if things aren't working as you expect. Are you missing serviceaccount permissions?

io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Pod]  with name: [happiness-service-17-flxlj]  in namespace: [dev]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62) ~[kubernetes-client-3.1.10.jar!/:na]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71) ~[kubernetes-client-3.1.10.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:206) ~[kubernetes-client-3.1.10.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:162) ~[kubernetes-client-3.1.10.jar!/:na]
	at org.springframework.cloud.kubernetes.StandardPodUtils.internalGetPod(StandardPodUtils.java:62) ~[spring-cloud-kubernetes-core-1.0.0.M2.jar!/:1.0.0.M2]
	at org.springframework.cloud.kubernetes.StandardPodUtils.lambda$new$0(StandardPodUtils.java:46) ~[spring-cloud-kubernetes-core-1.0.0.M2.jar!/:1.0.0.M2]
	at org.springframework.cloud.kubernetes.LazilyInstantiate.swapper(LazilyInstantiate.java:41) ~[spring-cloud-kubernetes-core-1.0.0.M2.jar!/:1.0.0.M2]
	at org.springframework.cloud.kubernetes.LazilyInstantiate.lambda$new$0(LazilyInstantiate.java:34) ~[spring-cloud-kubernetes-core-1.0.0.M2.jar!/:1.0.0.M2]
	at org.springframework.cloud.kubernetes.LazilyInstantiate.get(LazilyInstantiate.java:29) ~[spring-cloud-kubernetes-core-1.0.0.M2.jar!/:1.0.0.M2]
	at org.springframework.cloud.kubernetes.StandardPodUtils.isInsideKubernetes(StandardPodUtils.java:56) ~[spring-cloud-kubernetes-core-1.0.0.M2.jar!/:1.0.0.M2]
	at org.springframework.cloud.kubernetes.profile.KubernetesProfileApplicationListener.addKubernetesProfile(KubernetesProfileApplicationListener.java:52) ~[spring-cloud-kubernetes-core-1.0.0.M2.jar!/:1.0.0.M2]
	at org.springframework.cloud.kubernetes.profile.KubernetesApplicationContextInitializer.initialize(KubernetesApplicationContextInitializer.java:57) ~[spring-cloud-kubernetes-core-1.0.0.M2.jar!/:1.0.0.M2]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:649) ~[spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) ~[spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]
	at eu.eress.erex.config.ConfigApplication.main(ConfigApplication.java:16) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[service.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[service.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[service.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) ~[service.jar:na]
Caused by: javax.net.ssl.SSLProtocolException: Broken pipe (Write failed)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:126) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:988) ~[na:na]
	at okio.Okio$1.write(Okio.java:79) ~[okio-1.13.0.jar!/:na]
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180) ~[okio-1.13.0.jar!/:na]
	at okio.RealBufferedSink.flush(RealBufferedSink.java:216) ~[okio-1.13.0.jar!/:na]
	at okhttp3.internal.http2.Http2Writer.settings(Http2Writer.java:203) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http2.Http2Connection.start(Http2Connection.java:477) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http2.Http2Connection.start(Http2Connection.java:467) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:259) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:54) ~[kubernetes-client-3.1.10.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
	at io.fabric8.kubernetes.client.utils.HttpClientUtils$2.intercept(HttpClientUtils.java:93) ~[kubernetes-client-3.1.10.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.RealCall.execute(RealCall.java:69) ~[okhttp-3.8.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379) ~[kubernetes-client-3.1.10.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344) ~[kubernetes-client-3.1.10.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313) ~[kubernetes-client-3.1.10.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296) ~[kubernetes-client-3.1.10.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:770) ~[kubernetes-client-3.1.10.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:195) ~[kubernetes-client-3.1.10.jar!/:na]
	... 23 common frames omitted
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:na]
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110) ~[na:na]
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:320) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:983) ~[na:na]
	... 59 common frames omitted
```

**Comment by geoand** [comment]
As far as I am aware, the Kubernetes Client (which is one of the dependencies of this project) has not been tested with Java 11.
@gdubya would it be possible for you to check the functionality of your project using Java 8?

**Comment by gdubya** [comment]
This particular project is a bit tricky to quickly reconfigure for Java 8, but I have tested another app using minishift locally with Java 8 and it worked, so maybe that's it. Using minishift locally didn't have the same strict RBAC config as we have in our 'official' openshift cluster so I thought it might be related to that, but Java version is probably a more likely culprit.

**Comment by geoand** [comment]
@gdubya Thanks for the info!

Would it be possible perhaps for you to create and share a minimal project where the problem appears so we can investigate?

Thanks

**Comment by gdubya** [comment]
I have a project at https://github.com/gdubya/hello-gateway

If you deploy this with Java 8 it works (e.g. oc new-app codecentric/springboot-maven3-centos~https://github.com/gdubya/hello-gateway).

Another thought... it might actually be something to do with the debian image we use for Java 11, rather than Java 11 itself. I can't see any reason why the (few) dependencies of spring-cloud-starter-kubernetes would have any problem with java 11.

I'll look into that.

**Comment by geoand** [comment]
Cool!

**Comment by geoand** [comment]
> I tried a binary build using a Java 11 Docker image similar to the one we're using in the app that is experiencing the problem, and it worked ok (https://github.com/gdubya/hello-gateway/blob/master/Dockerfile). So now I'm back to thinking that it's a permission problem in Openshift rather than Java.
> 
> Are there any other roles that may be required for the service account other than "cluster-reader"?
> 
> How can I verify that the service account being used has that role in Openshift?

I would assume you are looking for commands specified [here](https://docs.openshift.com/container-platform/3.9/admin_guide/manage_rbac.html#managing-role-bindings)

FWIW, in past issues whenever we had trouble with RBAC, the stack trace already indicated that pretty well. In this case we there is nothing in the stack trace to indicate such a problem which makes me sceptical

**Comment by gdubya** [comment]
You're right. And all output indicates that the cluster-reader permission is set for the service account. So I have no idea what is causing the problem.

We tried a "full Java 11" build and that failed with the same message, so it's not related to our jlinked JDK.

I also tried disabling TLS 1.3 as there have been reports of some issues with that and Java 11, but no joy.

**Comment by geoand** [comment]
I have yet to try Java 11 to see if any Spring Cloud Kubernetes examples work, but hopefully that will change soon :)

**Comment by cmoulliard** [comment]
I did a quick test using your project top of openshift 3.11 = kubenetes 1.11 and I can't reproduce your error

https://github.com/ch007m/hello-jdk11#hello-gateway

**Comment by Alos** [comment]
I'm running in GKE with openjdk:11 with no issues

**Comment by spencergibb** [comment]
If you can provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem with Java 11 we can reopen.  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by keaz** [comment]
I had the same issue when I use jlinked openjdk jre 11. I fixed this issue by using normal openjdk 11.

**Comment by gdubya** [comment]
Just to give this issue some closure, we recently discovered that it _was_ due to the jlinked java image that we were using (thanks @keaz). We resolved it by adding `--bind-services` to the jlink command to ensure that the required modules were loaded.
