### ISSUE TITLE
How does the PropertySource reload work for HA config server?

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-kubernetes#39]
Reference to https://github.com/spring-cloud-incubator/spring-cloud-kubernetes#propertysource-reload 

Git can send notification to a URL but we want to have multiple config servers for high-availability. One option is to put them in a K8S service but then we need to build something in K8S to send notifications to all pods in the service.

**Comment by iocanel** [comment]
My understanding is that this part of documentation refers to the configmap and secret property sources and does not have to do with the config server stuff.

@nicolaferraro: can you please verify?

**Comment by nicolaferraro** [comment]
Yes, the reload functionality is related to secret and configmap property sources only. Internally, it should use the same path that the spring config server uses to trigger a reload, but it doesn't need a config server.
It's the pod itself that monitors the Kubernetes namespace and triggers a reload to the context as soon as a change event is detected (via websocket from the Openshift rest API by default).

**Comment by asarkar** [comment]
How do I dynamically refresh a config server K8S service? Or are you saying that is a better question for spring-cloud-config?

**Comment by Nareshkumarpr** [comment]
I have a error when I enable reload property,

spring.cloud.kubernetes.reload.enabled=true

Error Trace:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'propertyChangeWatcher': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: okhttp3.internal.Internal.setCallWebSocket(Lokhttp3/Call;)V
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.7.RELEASE.jar:1.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760) [spring-boot-1.3.7.RELEASE.jar:1.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360) [spring-boot-1.3.7.RELEASE.jar:1.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306) [spring-boot-1.3.7.RELEASE.jar:1.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) [spring-boot-1.3.7.RELEASE.jar:1.3.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) [spring-boot-1.3.7.RELEASE.jar:1.3.7.RELEASE]
	at com.example.BootFabricApplication.main(BootFabricApplication.java:14) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
Caused by: java.lang.NoSuchMethodError: okhttp3.internal.Internal.setCallWebSocket(Lokhttp3/Call;)V
	at okhttp3.ws.WebSocketCall.enqueue(WebSocketCall.java:108) ~[okhttp-ws-3.4.1.jar:na]
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.runWatch(WatchConnectionManager.java:125) ~[kubernetes-client-1.4.14.jar:na]
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.<init>(WatchConnectionManager.java:89) ~[kubernetes-client-1.4.14.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:545) ~[kubernetes-client-1.4.14.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:540) ~[kubernetes-client-1.4.14.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:59) ~[kubernetes-client-1.4.14.jar:na]
	at io.fabric8.spring.cloud.kubernetes.reload.EventBasedConfigurationChangeDetector.watch(EventBasedConfigurationChangeDetector.java:70) ~[spring-cloud-kubernetes-core-0.1.4.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	... 23 common frames omitted


I have also assigned role as below,
oc policy add-role-to-user view --serviceaccount=default

Still it  was failing for websocket error. Can you please help/guide on this?

**Comment by spencergibb** [comment]
Yes, they are unrelated.
