### ISSUE TITLE
java.lang.NoSuchMethodError: okio.ByteString.startsWith(Lokio/ByteString;)Z

### ISSUE THREAD

**Issue by sailor4242** [spring-cloud/spring-cloud-kubernetes#391]
Hi, I have just added "spring-cloud-starter-kubernetes-config"  to my project and it's failed to start with  : 
`java.lang.NoSuchMethodError: okio.ByteString.startsWith(Lokio/ByteString;)Z
	at okhttp3.internal.http2.Hpack$Writer.writeHeaders(Hpack.java:511)
	at okhttp3.internal.http2.Http2Writer.headers(Http2Writer.java:299)
	at okhttp3.internal.http2.Http2Writer.synStream(Http2Writer.java:127)
	at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:230)
	at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:205)
	at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:46)`

I am running SB - 2.1.1.RELEASE and SC - Greenwich.M3.

Could resolve this by adding "kubernetes-client" 4.2.2 explicitly.
Dunno, if i am doing something wrong, could anyone clarify please.

**Comment by geoand** [comment]
Hi,

Are you overriding the kubernetes-client in the project that you see the error in? Or are you perhaps using ok-http in your project?

**Comment by sailor4242** [comment]
no, i am not using it

**Comment by geoand** [comment]
@sailor4242 would it be possible to provide a reproducer project?

**Comment by sailor4242** [comment]
@geonad I can try, but it may take some time

**Comment by spencergibb** [comment]
How about start with your dependency tree `mvn dependency:tree` or the Gradle equivalent

**Comment by sailor4242** [comment]
@spencergibb, @geoand  Yes, sorry for disturbance, was getting it transitive.
