### ISSUE TITLE
KubernetesHealthIndicator fails on preemptible VMs on GCloud and does not recover

### ISSUE THREAD

**Issue by AndreasKl** [spring-cloud/spring-cloud-kubernetes#429]
On our development environment the `KubernetesHealthIndicator` fails with `{kubernetes=DOWN {inside=true, namespace=default, podName=ffp-cloud-gateway-rest-tenant-764c8c7d7b-s62c2, error=java.lang.IllegalArgumentException: Value must not be null}` and does not recover.

This is most likely due to passing a null value into `withDetail`.

In addition I was not able to deactivate the `KubernetesHealthIndicator` using the common way as `@ConditionalOnEnabledHealthIndicator` is missing.

**Comment by geoand** [comment]
Hi,

Very interesting, would it possible for you to provide some debug logs from when the application starts so we can understand why the error message is being generated?

**Comment by AndreasKl** [comment]
@geoand I added exception logging to the `KubernetesHealthIndicator` and will post the output asap.

**Comment by AndreasKl** [comment]
I see the following stacktrace:
```
exception: "java.lang.IllegalArgumentException: Value must not be null
	at org.springframework.util.Assert.notNull(Assert.java:198)
	at org.springframework.boot.actuate.health.Health$Builder.withDetail(Health.java:228)
	at com.rewedigital.fulfillment.cloudgateway.health.LoggingKubernetesHealthIndicator.doHealthCheck(LoggingKubernetesHealthIndicator.java:39)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.boot.actuate.health.HealthIndicatorReactiveAdapter.invoke(HealthIndicatorReactiveAdapter.java:48)
	at org.springframework.boot.actuate.health.HealthIndicatorReactiveAdapter.lambda$null$0(HealthIndicatorReactiveAdapter.java:43)
	at reactor.core.scheduler.ElasticScheduler$DirectScheduleTask.run(ElasticScheduler.java:292)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27)
	at org.springframework.cloud.sleuth.instrument.async.TraceCallable.call(TraceCallable.java:70)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by geoand** [comment]
Thanks for the info!

Unfortunately I don't think there is anything we can do on our end... It looks like you will have to manually do some null checking and only include the field when it's non null

**Comment by AndreasKl** [comment]
@geoand Maybe it could be considered a bug that the http call is only issued on application start and never updated, rendering the health check pretty useless.

**Comment by geoand** [comment]
That makes sense, but then again I don't know if Spring Cloud that in general... @ryanjbaxter, @spencergibb ?

**Comment by spencergibb** [comment]
There's no reason that can't be reworked to try again during certain conditions.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
