### ISSUE TITLE
NoSuchMethodError on OkHttpClient$Builder.pingInterval

### ISSUE THREAD

**Issue by joshfix** [spring-cloud/spring-cloud-kubernetes#45]
I've been using 0.2.0.BUILD-SNAPSHOT for a couple of weeks without issue.  As of this morning, I can successfully build my apps with the starter, but cannot run them.  Very early in bootstrap I get the following exception:

```/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/bin/java -Dspring.output.ansi.enabled=always -Didea.launcher.port=7537 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/lib/tools.jar:/Users/joshfix/boundless/bcs/bcs-edge-service/target/classes:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot-starter-web/1.5.1.RELEASE/spring-boot-starter-web-1.5.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot-starter/1.5.1.RELEASE/spring-boot-starter-1.5.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/1.5.1.RELEASE/spring-boot-starter-tomcat-1.5.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.11/tomcat-embed-core-8.5.11.jar:/Users/joshfix/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/8.5.11/tomcat-embed-el-8.5.11.jar:/Users/joshfix/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.5.11/tomcat-embed-websocket-8.5.11.jar:/Users/joshfix/.m2/repository/org/hibernate/hibernate-validator/5.3.4.Final/hibernate-validator-5.3.4.Final.jar:/Users/joshfix/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:/Users/joshfix/.m2/repository/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar:/Users/joshfix/.m2/repository/com/fasterxml/classmate/1.3.3/classmate-1.3.3.jar:/Users/joshfix/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.6/jackson-databind-2.8.6.jar:/Users/joshfix/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.6/jackson-core-2.8.6.jar:/Users/joshfix/.m2/repository/org/springframework/spring-web/4.3.6.RELEASE/spring-web-4.3.6.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/spring-beans/4.3.6.RELEASE/spring-beans-4.3.6.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/spring-webmvc/4.3.6.RELEASE/spring-webmvc-4.3.6.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/spring-expression/4.3.6.RELEASE/spring-expression-4.3.6.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-starter-zuul/1.2.5.RELEASE/spring-cloud-starter-zuul-1.2.5.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-starter/1.1.7.RELEASE/spring-cloud-starter-1.1.7.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/security/spring-security-rsa/1.0.3.RELEASE/spring-security-rsa-1.0.3.RELEASE.jar:/Users/joshfix/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.55/bcpkix-jdk15on-1.55.jar:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/1.5.1.RELEASE/spring-boot-starter-actuator-1.5.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-starter-ribbon/1.2.5.RELEASE/spring-cloud-starter-ribbon-1.2.5.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/retry/spring-retry/1.2.0.RELEASE/spring-retry-1.2.0.RELEASE.jar:/Users/joshfix/.m2/repository/com/netflix/ribbon/ribbon/2.2.0/ribbon-2.2.0.jar:/Users/joshfix/.m2/repository/com/netflix/ribbon/ribbon-transport/2.2.0/ribbon-transport-2.2.0.jar:/Users/joshfix/.m2/repository/io/reactivex/rxnetty-contexts/0.4.9/rxnetty-contexts-0.4.9.jar:/Users/joshfix/.m2/repository/io/reactivex/rxnetty-servo/0.4.9/rxnetty-servo-0.4.9.jar:/Users/joshfix/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/joshfix/.m2/repository/io/reactivex/rxnetty/0.4.9/rxnetty-0.4.9.jar:/Users/joshfix/.m2/repository/io/netty/netty-codec-http/4.0.27.Final/netty-codec-http-4.0.27.Final.jar:/Users/joshfix/.m2/repository/io/netty/netty-codec/4.0.27.Final/netty-codec-4.0.27.Final.jar:/Users/joshfix/.m2/repository/io/netty/netty-handler/4.0.27.Final/netty-handler-4.0.27.Final.jar:/Users/joshfix/.m2/repository/io/netty/netty-transport-native-epoll/4.0.27.Final/netty-transport-native-epoll-4.0.27.Final.jar:/Users/joshfix/.m2/repository/io/netty/netty-common/4.0.27.Final/netty-common-4.0.27.Final.jar:/Users/joshfix/.m2/repository/io/netty/netty-buffer/4.0.27.Final/netty-buffer-4.0.27.Final.jar:/Users/joshfix/.m2/repository/io/netty/netty-transport/4.0.27.Final/netty-transport-4.0.27.Final.jar:/Users/joshfix/.m2/repository/com/netflix/ribbon/ribbon-core/2.2.0/ribbon-core-2.2.0.jar:/Users/joshfix/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/Users/joshfix/.m2/repository/com/netflix/ribbon/ribbon-httpclient/2.2.0/ribbon-httpclient-2.2.0.jar:/Users/joshfix/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar:/Users/joshfix/.m2/repository/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar:/Users/joshfix/.m2/repository/com/sun/jersey/jersey-client/1.19.1/jersey-client-1.19.1.jar:/Users/joshfix/.m2/repository/com/sun/jersey/jersey-core/1.19.1/jersey-core-1.19.1.jar:/Users/joshfix/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar:/Users/joshfix/.m2/repository/com/sun/jersey/contribs/jersey-apache-client4/1.19.1/jersey-apache-client4-1.19.1.jar:/Users/joshfix/.m2/repository/com/netflix/ribbon/ribbon-loadbalancer/2.2.0/ribbon-loadbalancer-2.2.0.jar:/Users/joshfix/.m2/repository/com/netflix/netflix-commons/netflix-statistics/0.1.1/netflix-statistics-0.1.1.jar:/Users/joshfix/.m2/repository/io/reactivex/rxjava/1.1.10/rxjava-1.1.10.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-starter-archaius/1.2.5.RELEASE/spring-cloud-starter-archaius-1.2.5.RELEASE.jar:/Users/joshfix/.m2/repository/com/netflix/archaius/archaius-core/0.7.4/archaius-core-0.7.4.jar:/Users/joshfix/.m2/repository/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar:/Users/joshfix/.m2/repository/commons-configuration/commons-configuration/1.8/commons-configuration-1.8.jar:/Users/joshfix/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/Users/joshfix/.m2/repository/com/netflix/zuul/zuul-core/1.3.0/zuul-core-1.3.0.jar:/Users/joshfix/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/joshfix/.m2/repository/org/slf4j/slf4j-api/1.7.22/slf4j-api-1.7.22.jar:/Users/joshfix/.m2/repository/com/netflix/servo/servo-core/0.10.1/servo-core-0.10.1.jar:/Users/joshfix/.m2/repository/com/netflix/servo/servo-internal/0.10.1/servo-internal-0.10.1.jar:/Users/joshfix/.m2/repository/com/netflix/netflix-commons/netflix-commons-util/0.1.1/netflix-commons-util-0.1.1.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-starter-spectator/1.2.5.RELEASE/spring-cloud-starter-spectator-1.2.5.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-netflix-spectator/1.2.5.RELEASE/spring-cloud-netflix-spectator-1.2.5.RELEASE.jar:/Users/joshfix/.m2/repository/com/netflix/spectator/spectator-api/0.30.0/spectator-api-0.30.0.jar:/Users/joshfix/.m2/repository/com/netflix/spectator/spectator-reg-servo/0.30.0/spectator-reg-servo-0.30.0.jar:/Users/joshfix/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/joshfix/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar:/Users/joshfix/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/joshfix/.m2/repository/org/springframework/spring-core/4.3.6.RELEASE/spring-core-4.3.6.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot-actuator/1.5.1.RELEASE/spring-boot-actuator-1.5.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot/1.5.1.RELEASE/spring-boot-1.5.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/1.5.1.RELEASE/spring-boot-autoconfigure-1.5.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/spring-context/4.3.6.RELEASE/spring-context-4.3.6.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-netflix-hystrix-stream/1.2.5.RELEASE/spring-cloud-netflix-hystrix-stream-1.2.5.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot-starter-logging/1.5.1.RELEASE/spring-boot-starter-logging-1.5.1.RELEASE.jar:/Users/joshfix/.m2/repository/ch/qos/logback/logback-classic/1.1.9/logback-classic-1.1.9.jar:/Users/joshfix/.m2/repository/ch/qos/logback/logback-core/1.1.9/logback-core-1.1.9.jar:/Users/joshfix/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.22/jcl-over-slf4j-1.7.22.jar:/Users/joshfix/.m2/repository/org/slf4j/jul-to-slf4j/1.7.22/jul-to-slf4j-1.7.22.jar:/Users/joshfix/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.22/log4j-over-slf4j-1.7.22.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-commons/1.1.7.RELEASE/spring-cloud-commons-1.1.7.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/security/spring-security-crypto/4.2.1.RELEASE/spring-security-crypto-4.2.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-netflix-core/1.2.5.RELEASE/spring-cloud-netflix-core-1.2.5.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-stream/1.1.1.RELEASE/spring-cloud-stream-1.1.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot-starter-validation/1.5.1.RELEASE/spring-boot-starter-validation-1.5.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/integration/spring-integration-core/4.3.7.RELEASE/spring-integration-core-4.3.7.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/integration/spring-integration-jmx/4.3.7.RELEASE/spring-integration-jmx-4.3.7.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/spring-tuple/1.0.0.RELEASE/spring-tuple-1.0.0.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/integration/spring-integration-tuple/1.0.0.RELEASE/spring-integration-tuple-1.0.0.RELEASE.jar:/Users/joshfix/.m2/repository/com/netflix/hystrix/hystrix-core/1.5.6/hystrix-core-1.5.6.jar:/Users/joshfix/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.9/HdrHistogram-2.1.9.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-stream-binder-kafka/1.1.1.RELEASE/spring-cloud-stream-binder-kafka-1.1.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-stream-codec/1.1.1.RELEASE/spring-cloud-stream-codec-1.1.1.RELEASE.jar:/Users/joshfix/.m2/repository/com/esotericsoftware/kryo-shaded/3.0.3/kryo-shaded-3.0.3.jar:/Users/joshfix/.m2/repository/com/esotericsoftware/minlog/1.3.0/minlog-1.3.0.jar:/Users/joshfix/.m2/repository/org/springframework/integration/spring-integration-kafka/2.0.1.RELEASE/spring-integration-kafka-2.0.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/apache/kafka/kafka_2.11/0.9.0.1/kafka_2.11-0.9.0.1.jar:/Users/joshfix/.m2/repository/com/101tec/zkclient/0.7/zkclient-0.7.jar:/Users/joshfix/.m2/repository/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.jar:/Users/joshfix/.m2/repository/org/scala-lang/modules/scala-xml_2.11/1.0.4/scala-xml_2.11-1.0.4.jar:/Users/joshfix/.m2/repository/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.jar:/Users/joshfix/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar:/Users/joshfix/.m2/repository/net/sf/jopt-simple/jopt-simple/3.2/jopt-simple-3.2.jar:/Users/joshfix/.m2/repository/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar:/Users/joshfix/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar:/Users/joshfix/.m2/repository/io/netty/netty/3.7.0.Final/netty-3.7.0.Final.jar:/Users/joshfix/.m2/repository/org/apache/kafka/kafka-clients/0.9.0.1/kafka-clients-0.9.0.1.jar:/Users/joshfix/.m2/repository/org/xerial/snappy/snappy-java/1.1.1.7/snappy-java-1.1.1.7.jar:/Users/joshfix/.m2/repository/net/jpountz/lz4/lz4/1.2.0/lz4-1.2.0.jar:/Users/joshfix/.m2/repository/org/springframework/kafka/spring-kafka/1.1.2.RELEASE/spring-kafka-1.1.2.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-starter-hystrix/1.2.5.RELEASE/spring-cloud-starter-hystrix-1.2.5.RELEASE.jar:/Users/joshfix/.m2/repository/com/netflix/hystrix/hystrix-metrics-event-stream/1.5.6/hystrix-metrics-event-stream-1.5.6.jar:/Users/joshfix/.m2/repository/com/netflix/hystrix/hystrix-serialization/1.5.6/hystrix-serialization-1.5.6.jar:/Users/joshfix/.m2/repository/com/fasterxml/jackson/module/jackson-module-afterburner/2.8.6/jackson-module-afterburner-2.8.6.jar:/Users/joshfix/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.8.6/jackson-dataformat-cbor-2.8.6.jar:/Users/joshfix/.m2/repository/com/netflix/hystrix/hystrix-javanica/1.5.6/hystrix-javanica-1.5.6.jar:/Users/joshfix/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/Users/joshfix/.m2/repository/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar:/Users/joshfix/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar:/Users/joshfix/.m2/repository/org/aspectj/aspectjweaver/1.8.9/aspectjweaver-1.8.9.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-config-client/1.2.2.RELEASE/spring-cloud-config-client-1.2.2.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-context/1.1.7.RELEASE/spring-cloud-context-1.1.7.RELEASE.jar:/Users/joshfix/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-starter-sleuth/1.1.2.RELEASE/spring-cloud-starter-sleuth-1.1.2.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot-starter-aop/1.5.1.RELEASE/spring-boot-starter-aop-1.5.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-sleuth-core/1.1.2.RELEASE/spring-cloud-sleuth-core-1.1.2.RELEASE.jar:/Users/joshfix/.m2/repository/org/aspectj/aspectjrt/1.8.9/aspectjrt-1.8.9.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-starter-kubernetes/0.2.0.BUILD-SNAPSHOT/spring-cloud-starter-kubernetes-0.2.0.BUILD-20170303.101511-597.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-kubernetes-core/0.2.0.BUILD-SNAPSHOT/spring-cloud-kubernetes-core-0.2.0.BUILD-20170303.101400-597.jar:/Users/joshfix/.m2/repository/io/fabric8/kubernetes-client/2.2.0/kubernetes-client-2.2.0.jar:/Users/joshfix/.m2/repository/io/fabric8/kubernetes-model/1.0.67/kubernetes-model-1.0.67.jar:/Users/joshfix/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.8.6/jackson-module-jaxb-annotations-2.8.6.jar:/Users/joshfix/.m2/repository/com/squareup/okhttp3/okhttp/3.3.1/okhttp-3.3.1.jar:/Users/joshfix/.m2/repository/com/squareup/okio/okio/1.8.0/okio-1.8.0.jar:/Users/joshfix/.m2/repository/com/squareup/okhttp3/logging-interceptor/3.6.0/logging-interceptor-3.6.0.jar:/Users/joshfix/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.8.6/jackson-dataformat-yaml-2.8.6.jar:/Users/joshfix/.m2/repository/io/fabric8/zjsonpatch/0.3.0/zjsonpatch-0.3.0.jar:/Users/joshfix/.m2/repository/com/github/mifmif/generex/1.0.1/generex-1.0.1.jar:/Users/joshfix/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar:/Users/joshfix/.m2/repository/org/springframework/cloud/spring-cloud-kubernetes-discovery/0.2.0.BUILD-SNAPSHOT/spring-cloud-kubernetes-discovery-0.2.0.BUILD-20170303.101426-597.jar:/Users/joshfix/.m2/repository/org/projectlombok/lombok/1.16.12/lombok-1.16.12.jar:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot-starter-amqp/1.5.1.RELEASE/spring-boot-starter-amqp-1.5.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/spring-messaging/4.3.6.RELEASE/spring-messaging-4.3.6.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/amqp/spring-rabbit/1.7.0.RELEASE/spring-rabbit-1.7.0.RELEASE.jar:/Users/joshfix/.m2/repository/com/rabbitmq/http-client/1.1.0.RELEASE/http-client-1.1.0.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/spring-tx/4.3.6.RELEASE/spring-tx-4.3.6.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/amqp/spring-amqp/1.7.0.RELEASE/spring-amqp-1.7.0.RELEASE.jar:/Users/joshfix/.m2/repository/com/rabbitmq/amqp-client/4.0.1/amqp-client-4.0.1.jar:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot-starter-security/1.5.1.RELEASE/spring-boot-starter-security-1.5.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/spring-aop/4.3.6.RELEASE/spring-aop-4.3.6.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/security/spring-security-config/4.2.1.RELEASE/spring-security-config-4.2.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/security/spring-security-core/4.2.1.RELEASE/spring-security-core-4.2.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/security/spring-security-web/4.2.1.RELEASE/spring-security-web-4.2.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/boot/spring-boot-starter-redis/1.4.1.RELEASE/spring-boot-starter-redis-1.4.1.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/data/spring-data-redis/1.8.0.RELEASE/spring-data-redis-1.8.0.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/data/spring-data-keyvalue/1.2.0.RELEASE/spring-data-keyvalue-1.2.0.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/data/spring-data-commons/1.13.0.RELEASE/spring-data-commons-1.13.0.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/spring-oxm/4.3.6.RELEASE/spring-oxm-4.3.6.RELEASE.jar:/Users/joshfix/.m2/repository/org/springframework/spring-context-support/4.3.6.RELEASE/spring-context-support-4.3.6.RELEASE.jar:/Users/joshfix/.m2/repository/redis/clients/jedis/2.9.0/jedis-2.9.0.jar:/Users/joshfix/.m2/repository/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar:/Users/joshfix/.m2/repository/com/auth0/java-jwt/3.1.0/java-jwt-3.1.0.jar:/Users/joshfix/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/joshfix/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.55/bcprov-jdk15on-1.55.jar:/Users/joshfix/.m2/repository/joda-time/joda-time/2.9.7/joda-time-2.9.7.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain com.boundlessgeo.bcs.edge.EdgeApplication
10:17:38.391 [main] DEBUG io.fabric8.kubernetes.client.Config - Trying to configure client from Kubernetes config...
10:17:38.403 [main] DEBUG io.fabric8.kubernetes.client.Config - Found for Kubernetes config at: [/Users/me/.kube/config].
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.cloud.kubernetes.profile.KubernetesApplicationContextInitializer
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:423)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:402)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:393)
	at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:260)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:236)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at com.boundlessgeo.bcs.edge.EdgeApplication.main(EdgeApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.kubernetes.profile.KubernetesApplicationContextInitializer]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder.pingInterval(JLjava/util/concurrent/TimeUnit;)Lokhttp3/OkHttpClient$Builder;
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:419)
	... 12 more
Caused by: java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder.pingInterval(JLjava/util/concurrent/TimeUnit;)Lokhttp3/OkHttpClient$Builder;
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:115)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:45)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:37)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:108)
	at org.springframework.cloud.kubernetes.profile.KubernetesApplicationContextInitializer.<init>(KubernetesApplicationContextInitializer.java:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 13 more

Process finished with exit code 1
```

This error occurs both locally and on kubernetes.

**Comment by joshfix** [comment]
Excluding okhttp and manually specifying the latest version seems to circumvent the issue.

```
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-kubernetes</artifactId>
            <version>0.2.0.BUILD-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>okhttp3</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by spencergibb** [comment]
Can you run `./mvnw -X dependency:tree` against your project (before the fix) and see where the dependency came from?
 
I just fixed an issue regarding this here https://github.com/spring-cloud/spring-cloud-netflix/issues/1752

**Comment by joshfix** [comment]
Sure:

```
[INFO] +- org.springframework.cloud:spring-cloud-starter-kubernetes:jar:0.2.0.BUILD-SNAPSHOT:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-kubernetes-core:jar:0.2.0.BUILD-SNAPSHOT:compile
[INFO] |  |  \- io.fabric8:kubernetes-client:jar:2.2.0:compile
[INFO] |  |     +- io.fabric8:kubernetes-model:jar:1.0.67:compile
[INFO] |  |     |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.8.6:compile
[INFO] |  |     +- com.squareup.okhttp3:okhttp:jar:3.3.1:compile
[INFO] |  |     |  \- com.squareup.okio:okio:jar:1.8.0:compile
[INFO] |  |     +- com.squareup.okhttp3:logging-interceptor:jar:3.6.0:compile
[INFO] |  |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.8.6:compile
[INFO] |  |     +- io.fabric8:zjsonpatch:jar:0.3.0:compile
[INFO] |  |     \- com.github.mifmif:generex:jar:1.0.1:compile
[INFO] |  |        \- dk.brics.automaton:automaton:jar:1.11-8:compile
```

**Comment by spencergibb** [comment]
Looks like upgrading k8s-client to 2.2.1 will help as well http://search.maven.org/#artifactdetails%7Cio.fabric8%7Ckubernetes-client-project%7C2.2.1%7Cpom

**Comment by iocanel** [comment]
Our current master is using kubernetes-client version 2.2.0 which is already using `okhttp` 3.6.0.

The fact that your dependency tree shows 3.3.1 instead of 3.6.0 makes me think that there is some short of dependencyManagement affecting you.

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.
