### ISSUE TITLE
KubernetesApplicationContextInitializer error when kubernetes is disabled

### ISSUE THREAD

**Issue by Adamovskiy** [spring-cloud/spring-cloud-kubernetes#485]
I have `spring.cloud.kubernetes.enabled` property set to `false` via environment. But it still tries to build kubernetes client config, and prints stacktrace to std out:

```
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[kubernetes-client-4.1.0.jar:na]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[kubernetes-client-4.1.0.jar:na]
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237) ~[kubernetes-client-4.1.0.jar:na]
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190) ~[kubernetes-client-4.1.0.jar:na]
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:177) ~[kubernetes-client-4.1.0.jar:na]
	at io.fabric8.kubernetes.client.Config.loadFromKubeconfig(Config.java:531) [kubernetes-client-4.1.0.jar:na]
	at io.fabric8.kubernetes.client.Config.tryKubeConfig(Config.java:452) [kubernetes-client-4.1.0.jar:na]
	at io.fabric8.kubernetes.client.Config.autoConfigure(Config.java:204) [kubernetes-client-4.1.0.jar:na]
	at io.fabric8.kubernetes.client.Config.<init>(Config.java:192) [kubernetes-client-4.1.0.jar:na]
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:16) [kubernetes-client-4.1.0.jar:na]
	at io.fabric8.kubernetes.client.ConfigBuilder.<init>(ConfigBuilder.java:13) [kubernetes-client-4.1.0.jar:na]
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:47) [kubernetes-client-4.1.0.jar:na]
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:83) [kubernetes-client-4.1.0.jar:na]
	at org.springframework.cloud.kubernetes.profile.KubernetesApplicationContextInitializer.lambda$new$0(KubernetesApplicationContextInitializer.java:41) [spring-cloud-kubernetes-core-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.cloud.kubernetes.LazilyInstantiate.swapper(LazilyInstantiate.java:41) ~[spring-cloud-kubernetes-core-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.cloud.kubernetes.LazilyInstantiate.lambda$new$0(LazilyInstantiate.java:34) ~[spring-cloud-kubernetes-core-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.cloud.kubernetes.LazilyInstantiate.get(LazilyInstantiate.java:29) ~[spring-cloud-kubernetes-core-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.cloud.kubernetes.profile.KubernetesApplicationContextInitializer.initialize(KubernetesApplicationContextInitializer.java:57) [spring-cloud-kubernetes-core-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:649) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at com.arrival.adt.profiles.api.profiles-api.main(Application.kt:32) ~[classes/:na]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "expirationTimestamp" (class io.fabric8.kubernetes.client.Config$ExecCredentialStatus), not marked as ignorable (one known property: "token"])
...
```
First of all, it would be nice to print it with logger, not to the output directly. And anyway, I think there should be a way to avoid any kubernetes interaction by config. There already was https://github.com/spring-cloud/spring-cloud-kubernetes/issues/131, which fixed part of this problem.

**Comment by TYsewyn** [comment]
Can I kindly ask you which release train of Spring Cloud you are using?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
