### ISSUE TITLE
Document using bootstrap to disable

### ISSUE THREAD

**Issue by yeshwanthvshenoy** [spring-cloud/spring-cloud-kubernetes#493]
**Describe the bug**
Spring Cloud Kubernetes Leader is trying to create a new Kubernetes client on application startup even when the `spring.cloud.kubernetes.leader.enabled=false` and `spring.cloud.kubernetes.leader.autoStartup=false` are set in the application.properties.

**Sample**
Let's assume I am not running minikube locally and I have the spring-cloud-kubernetes-leader added in my dependencies and have the set the properties as above. I am getting an error like this:

```
ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoSuchMethodError: 'okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.sslSocketFactory(javax.net.ssl.SSLSocketFactory, javax.net.ssl.X509TrustManager)'
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:88)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:55)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:47)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:83)
	at org.springframework.cloud.kubernetes.profile.KubernetesProfileEnvironmentPostProcessor.postProcessEnvironment(KubernetesProfileEnvironmentPostProcessor.java:45)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:179)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:203)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:71)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at com.test.main(Application.java:11)
```

Not to mention, I also have the `com.squareup.okhttp3.okhttp` dependency added to my project as well. I debugged this further and I can see that the Kubernetes Client is being created irrespective of the value of the property. It is being created at [KubernetesProfileEnvironmentPostProcessor.java#L52](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-core/src/main/java/org/springframework/cloud/kubernetes/profile/KubernetesProfileEnvironmentPostProcessor.java#L52). Ideally, I am not expecting it to create a client since my intention is specified by the properties. Is this a valid bug that can be fixed? Is there any workaround or fixes to this problem?

**Comment by geoand** [comment]
cc @gytis

**Comment by seletz** [comment]
Just bumped into the same issue.
Adding `spring.cloud.kubernetes.enabled=false` to application.yaml is ignored.

The property **is** used if added to the `bootstrap.yaml` file.

I'm using 1.1.0.RELEASE.

This bug hits me when doing integration tests and deploying on non-k8s environments.

**Comment by spencergibb** [comment]
if you are using config it happens in bootstrap and the property must be present there.

**Comment by seletz** [comment]
@spencergibb  OK, I see.  Would there be another way to disable s.c.k8s for e.g. integration testing?

**Comment by seletz** [comment]
Ah, I see.  For my use case -- **only** enabling the thing when on K8S -- having:
- `spring.cloud.kubernetes.enabled=false` in `bootstrap.properties`
- `SPRING_CLOUD_KUBERNETES_ENABLED=true` in the k8s deployment spec does the trick.

Maybe this would be worth mentioning in the docs, or am I doing things wrong?

**Comment by spencergibb** [comment]
better docs are always beneficial.

**Comment by yeshwanthvshenoy** [comment]
@spencergibb When trying it out when `bootstrap.yaml` things are working as expected. Can we get this updated in the docs please? cc: @seletz

**Comment by ryanjbaxter** [comment]
This has already been documented as part of other changes
