### ISSUE TITLE
 Class not found KubernetesProfileEnvironmentPostProcessor

### ISSUE THREAD

**Issue by yuanqingx** [spring-cloud/spring-cloud-kubernetes#497]
**Describe the bug**
I tried 1.1.0.RELEASE,1.0.4.RELEASE, both of this versions has the problem. I don't know 1.0.3.RELEASE ,1.0.2.RELEASE  have the same error, but 1.0.1.RELEASE is normal, it's another class name.
When I debug, I found the class name is error, it has some space at the last. The name from the **spring.factories** 

```
org.springframework.boot.env.EnvironmentPostProcessor=\
org.springframework.cloud.kubernetes.profile.KubernetesProfileEnvironmentPostProcessor  
```

KubernetesProfileEnvironmentPostProcessor__(here is two space !!!!!!!), waster time , waster life, WTF.

so, ClassNotFoundException ↓
`Class.forName("org.springframework.cloud.kubernetes.profile.KubernetesProfileEnvironmentPostProcessor  ")`

**Sample**
```
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.kubernetes.profile.KubernetesProfileEnvironmentPostProcessor  
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:275) ~[spring-core-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:155) ~[spring-core-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	... 32 more
```

**Comment by ryanjbaxter** [comment]
Can you please provide details on how to reproduce this issue?  I would think that nearly all of our tests would fail if the spaces at the end were not removed by some code.

**Comment by yuanqingx** [comment]
I uesd Spring Boot 2.0.6.RELEASE.
In the org.springframework.core.io.support.SpringFactoriesLoader#loadSpringFactories,
it’s not trim the class name. So class not found.
And I tried the 2.2.2.RELEASE,it’s ok.
Your should eliminate the space...

![2](https://user-images.githubusercontent.com/39399831/70765756-a0e6c680-1d96-11ea-986e-4db27093dce2.png)
![3](https://user-images.githubusercontent.com/39399831/70765757-a17f5d00-1d96-11ea-8ee7-56f3e8345f9e.png)

**Comment by ryanjbaxter** [comment]
Spring Boot 2.0.x is EOL so I am going to close this
