### ISSUE TITLE
The `getScheme` method in of `KubernetesServiceInstance.java` class should not returns extra "://".

### ISSUE THREAD

**Issue by wansong** [spring-cloud/spring-cloud-kubernetes#520]
Sorry, this maybe a duplicate issue of [BlockingLoadBalancerClient does not work with KubernetesDiscoveryClient](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/486)
--------------------------------------------------------------------------

**Describe the bug**
In a Spring cloud project with version of `Hoxton.SR1`, i use `org.springframework.cloud:spring-cloud-starter-kubernetes` dependency to integrate the project with Kubernetes. The final version of the jar is `spring-cloud-kubernetes-discovery-1.1.1.RELEASE.jar`. When i use `@EnableDiscoveryClient` and a `RestTemplate` bean to communicate to a Kubernetes Service from the project that is deployed in a Pod within a Kubernetes cluster, i get following exception. But in fact, all Kubernetes service is correct, i can manually call the Kubernetes Service with a curl command from the same Pod as the project is deployed.

```
java.net.URISyntaxException: Expected hostname at index 7: http://://172.17.0.8:8004/
	at java.base/java.net.URI$Parser.fail(URI.java:2913) ~[na:na]
	at java.base/java.net.URI$Parser.failExpecting(URI.java:2919) ~[na:na]
	at java.base/java.net.URI$Parser.parseHostname(URI.java:3451) ~[na:na]
	at java.base/java.net.URI$Parser.parseServer(URI.java:3297) ~[na:na]
	at java.base/java.net.URI$Parser.parseAuthority(URI.java:3216) ~[na:na]
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3158) ~[na:na]
	at java.base/java.net.URI$Parser.parse(URI.java:3114) ~[na:na]
	at java.base/java.net.URI.<init>(URI.java:685) ~[na:na]
	at org.springframework.web.util.HierarchicalUriComponents.toUri(HierarchicalUriComponents.java:522) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.cloud.client.loadbalancer.LoadBalancerUriTools.doReconstructURI(LoadBalancerUriTools.java:111) ~[spring-cloud-commons-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.cloud.client.loadbalancer.LoadBalancerUriTools.reconstructURI(LoadBalancerUriTools.java:95) ~[spring-cloud-commons-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.reconstructURI(BlockingLoadBalancerClient.java:75) ~[spring-cloud-loadbalancer-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.cloud.client.loadbalancer.ServiceRequestWrapper.getURI(ServiceRequestWrapper.java:43) ~[spring-cloud-commons-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:98) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.cloud.client.loadbalancer.LoadBalancerRequestFactory.lambda$createRequest$0(LoadBalancerRequestFactory.java:61) ~[spring-cloud-commons-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.execute(BlockingLoadBalancerClient.java:62) ~[spring-cloud-loadbalancer-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.execute(BlockingLoadBalancerClient.java:55) ~[spring-cloud-loadbalancer-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.cloud.client.loadbalancer.LoadBalancerInterceptor.intercept(LoadBalancerInterceptor.java:58) ~[spring-cloud-commons-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:77) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:742) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:361) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
	at com.xxxxxxxxxx.springcloud.k8sclient.SpringCloudKubernetesController.viaSpringCloud(K8sClientApplication.java:178) ~[classes!/:na]
```

**I have debug the issue and found the reason is caused by The `getScheme` method in `KubernetesServiceInstance.java` class. A schema should not contain "://" suffix, that is to say, the method should return "http" and "https" instead of "http://" and "https://". Please see more from following code.**
[A same post issue](https://github.com/spring-cloud/spring-cloud-commons/issues/661)

```java
package org.springframework.cloud.kubernetes.discovery;
// Omit more code
public class KubernetesServiceInstance implements ServiceInstance {

        // Following comments are added by wansong
	// Here should be "http" and "https" instead of "http://" and "https://",
	// Need to remove the suffix "://" from a scheme.
	private static final String HTTP_PREFIX = "http://";
	private static final String HTTPS_PREFIX = "https://";

	// Omit more code

	@Override
	public String getScheme() {
		return isSecure() ? HTTPS_PREFIX : HTTP_PREFIX;
	}
}
```

**Comment by wansong** [comment]
Sorry, i have found a duplicate issue [here](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/486)
