### ISSUE TITLE
Netflix-ribbon not work with spring-cloud-starter-kubernetes

### ISSUE THREAD

**Issue by DmitryevichD** [spring-cloud/spring-cloud-kubernetes#555]
Hello.
I update spring cloud to Hoxton.SR4 and my ribbon.
After read this [issue](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/530#issuecomment-599075811) my dependency is
```groovy
implementation 'org.springframework.cloud:spring-cloud-starter-kubernetes'
implementation 'org.springframework.cloud:spring-cloud-starter-netflix-ribbon'
```
with new version, when I send request by feignclient, I throw  exception:
```java
java.lang.RuntimeException: com.netflix.client.ClientException: Load balancer does not have available server for client: sms
at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:90)
at org.springframework.cloud.sleuth.instrument.web.client.feign.TraceLoadBalancerFeignClient.execute(TraceLoadBalancerFeignClient.java:70)
at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:110)
at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:80)
at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
at com.sun.proxy.$Proxy194.sendSms(Unknown Source)
```

how to make work netflix-ribbon?

**Comment by DmitryevichD** [comment]
My problem solved

```java
@Configuration
@ConditionalOnProperty(value = "spring.cloud.kubernetes.enabled")
@AutoConfigureAfter(RibbonAutoConfiguration.class)
@RibbonClients(defaultConfiguration = KubernetesServerListConfiguration.class)
public class KubernetesRibbonConfiguration {
}
```
```java
public class KubernetesServerListConfiguration {

    @Bean
    public ServerList<Server> ribbonServerList(KubernetesClient client, IClientConfig config) {
        KubernetesServerList serverList = new KubernetesServerList(client);
        serverList.initWithNiwsConfig(config);
        return serverList;
    }

    @Slf4j
    @RequiredArgsConstructor
    public static class KubernetesServerList extends AbstractServerList<Server> implements ServerList<Server> {

        private final KubernetesClient client;

        private String serviceId;
        private String namespace;

        @Override
        public void initWithNiwsConfig(IClientConfig clientConfig) {
            this.serviceId = clientConfig.getClientName();
            this.namespace = client.getNamespace();
        }

        @Override
        public List<Server> getInitialListOfServers() {
            return Collections.emptyList();
        }

        @Override
        public List<Server> getUpdatedListOfServers() {
            val endpoints = client.endpoints().inNamespace(namespace).withName(serviceId).get();

            val result = new ArrayList<Server>();

            if (endpoints != null) {
                for (EndpointSubset subset : endpoints.getSubsets()) {
                    addEndpointSubsetToResultList(subset, result);
                }
            } else {
                log.warn("Did not find any endpoints in ribbon in namespace [{}] for name [{}]", namespace, serviceId);
            }

            return result;
        }

        private void addEndpointSubsetToResultList(EndpointSubset subset, ArrayList<Server> result) {
            for (EndpointPort port : subset.getPorts()) {
                addEndpointSubsetToResultList(subset.getAddresses(), port, result);
            }
        }

        private void addEndpointSubsetToResultList(List<EndpointAddress> addresses, EndpointPort port, ArrayList<Server> result) {
            for (EndpointAddress address : addresses) {
                result.add(new Server(address.getIp(), port.getPort()));
            }
        }
    }
}
```

**Comment by Alos** [comment]
I have the same issue, is the implementation of ribbon going away in spring cloud Hoxton.SR4?

**Comment by Alos** [comment]
I see that there is no implementation of spring-cloud-kubernetes-ribbon included with `spring-cloud-starter-kubernetes-all` and there is no matching version for `1.1.3.RELEASE`

https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-kubernetes-ribbon

**Comment by spencergibb** [comment]
Ribbon was removed in master (for ilford) and by some confusion it was removed in Hoxton). It will be restored. 4fa4b1123097fd935cae65094426916cc1badd9e will be reverted as well.

**Comment by Alos** [comment]
Thanks for the quick solution @spencergibb! 

On a related note. The ribbon-less implementation currently in master does not work with FeignClients. Are there any plans on bringing back this functionality? What was the reasoning for removing the old ribbon implementation? is there a proposal or design doc?

**Comment by ryanjbaxter** [comment]
@Alos we removed Ribbon because Netflix has moved it to maintenance mode and we have an alternative implementation in Spring Cloud Loadbalancer.  We decided to remove things in master as our next release will be a major release for Spring Cloud and we have the opportunity to make breaking changes.  

Please open a separate issue about FeignClients not working.

**Comment by Alos** [comment]
@ryanjbaxter thanks! I've created #571 Let me know if more information is required
