### ISSUE TITLE
local develop support ?

### ISSUE THREAD

**Issue by lanmingle** [spring-cloud/spring-cloud-kubernetes#568]
local add .kube/config (admin)

``` bash

$ kubectl cluster-info
Kubernetes master is running at https://rancher.qingyueyun.com/k8s/clusters/c-qzcsw
CoreDNS is running at https://rancher.qingyueyun.com/k8s/clusters/c-qzcsw/api/v1/namespaces/kube-system/services/kube-dns:dns-tcp/proxy

```

debug sun.net.www.http.HttpClient.openServer

``` java

    public void openServer(String server, int port) throws IOException {
        serverSocket = doConnect(server, port);
        ...
    }

```

output:

``` bash

sun.net.www.http.HttpClient(http://192.168.1.95:8080/producer/producer?producer=distributor-call)

```

log:

``` java

..  - 36   - INFO  - SN=[spring-cloud-distributor-demo:] - distributor - pResult=Result(data=NO, date=null, path=null, method=null, code=rest.producer.codes.feature.failure, error=null, status=null, message=null)
..  72   - DEBUG - SN=[spring-cloud-distributor-demo:] - [ConsumerApi#consumer] ---> GET http://spring-cloud-consumer-demo/consumer/consumer?consumer=distributor-call HTTP/1.1
..  - 72   - DEBUG - SN=[spring-cloud-distributor-demo:] - [ConsumerApi#consumer] Accept-Encoding: gzip
..  - 72   - DEBUG - SN=[spring-cloud-distributor-demo:] - [ConsumerApi#consumer] Accept-Encoding: deflate
.. - 72   - DEBUG - SN=[spring-cloud-distributor-demo:] - [ConsumerApi#consumer] ---> END HTTP (0-byte body)
.. - 39   - INFO  - SN=[spring-cloud-distributor-demo:] - distributor - cResult=Result(data=null, date=null, path=null, method=null, code=rest.consumer.codes.feature.failure, error=null, status=null, message=null)
.. - 41   - INFO  - SN=[spring-cloud-distributor-demo:] - distributor - distributor=sadasdzxc
.. - 72   - DEBUG - SN=[spring-cloud-distributor-demo:] - [ProducerApi#producer] <--- ERROR SocketTimeoutException: connect timed out (182292ms)
.. java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at feign.Client$Default.convertResponse(Client.java:108)
	at feign.Client$Default.execute(Client.java:104)
	at org.springframework.cloud.openfeign.loadbalancer.FeignBlockingLoadBalancerClient.execute(FeignBlockingLoadBalancerClient.java:78)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:109)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

maven:

``` xml

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>net.rakugakibox.spring.boot</groupId>
            <artifactId>orika-spring-boot-starter</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-web</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-spring-ui</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.spring4all</groupId>
            <artifactId>swagger-spring-boot-starter</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-kubernetes-all</artifactId>
            <scope>compile</scope>
        </dependency>

```

bootstrap.yaml

``` yaml

feign:

  hystrix:
    enabled: true

  compression:
    request:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
      min-request-size: 2048
    response:
      enabled: true
      useGzipDecoder: true

  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 3000
        loggerLevel: full

  httpclient:
    disable-ssl-validation: true

spring:

  cloud:

    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enabled: true
      cache:
        enabled: true
        ttl: 30

    inetutils:
      ignored-interfaces:
        - eth1
        - eth2
        - lo
        - docker0
        - veth.*
      preferred-networks:
        - 192.168
        - 10.0
      use-only-site-local-interfaces: false

    kubernetes:
      config:
        enabled: true
      secrets:
        enabled: true
      reload:
        enabled: true
      discovery:
        enabled: true
        all-namespaces: true

  application:
    name: spring-cloud-distributor-demo

logging:
  level:
    "org.springframework.boot.actuate.endpoint": error

```

version:

``` xml

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.1.RELEASE</version>
        <relativePath/>
    </parent>
   
    ....

    <spring-cloud-dependencies.version>Hoxton.SR5</spring-cloud-dependencies.version>

```

idea:

local kube get ingress

eg:

local server -> local kube -> local kube get svc(ip) ? debug : get ingress (http://spring-cloud-consumer-demo/consumer/consumer replace http://spring-cloud-consumer-demo.dev.qingyueyun.com )

my local develop：

``` java

@FeignClient(
        name = "${api.consumer.name}",
        url = "${api.consumer.url}",
        contextId = "consumerApi",
        fallback = ConsumerFallback.class,
        path = "/consumer"
)
public interface ConsumerApi {

    @GetMapping("/consumer")
    Result<Consumer> consumer(@RequestParam("consumer") String consumer);

}

```

``` yaml

api:
  producer:
    name: spring-cloud-producer-demo
    url:
    #url: http://localhost:8080
  consumer:
    name: spring-cloud-consumer-demo
    url:
    #url: http://localhost:8081

logging:
  level:
    com.qingyueyun.example.producer.api: debug
    com.qingyueyun.example.consumer.api: debug

```

**Comment by lanmingle** [comment]
local:  kubectl get ingresses

``` bash
$ kubectl get ingresses  ...
NAMESPACE      NAME                            HOSTS                                              ADDRESS   PORTS   AGE
dev-example    spring-cloud-consumer-demo      spring-cloud-consumer-demo.dev.qingyueyun.com                80      25h
dev-example    spring-cloud-distributor-demo   spring-cloud-distributor-demo.dev.qingyueyun.com             80      25h
dev-example    spring-cloud-producer-demo      spring-cloud-producer-demo.dev.qingyueyun.com                80      25h

```
