### ISSUE TITLE
FeignClients do not currently work without the spring-cloud-kubernetes-ribbon implementation

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-kubernetes#571]
Using the latest version of Spring Cloud Kubernetes without the spring-cloud-kubernetes-ribbon implementation causes FeignClients to not work:

```
com.netflix.client.ClientException: Load balancer does not have available server for client: my-awesome-service
```

Services are running in the same Kubernetes cluster, same namespace and was working with the spring-cloud-kubernetes-ribbon implementation. 

The current project is set up with `Hoxton.SR5` and :

```XML

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-hystrix</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-kubernetes-all</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-openfeign</artifactId>
    </dependency>
...

 <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${versions.spring-cloud}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
  </dependencyManagement>
```

**Comment by ryanjbaxter** [comment]
Can you provide the entire sample project?

**Comment by Alos** [comment]
Hey!

I created a sample project: https://github.com/Alos/K8sFeignClientExample

In this example I create 2 services, the `cat-service` that exposes an endpoint that just returns a list of `Cat` objects:

```java
@GetMapping("/api/v1/cats")
  public List<Cat> getAllCats()
```

The dog-service has another endpoint that tries to access the cats using a FeignClient:

```java
@RestController
@RequiredArgsConstructor
public class DogController {

  private final CatClient catClient;

  @GetMapping("/api/v1/talk")
  public List<Cat> talkWithCatService() {
    List<Cat> catsFromTheCatService = catClient.getAllCats();
    return catsFromTheCatService;
  }
}
```
The FeignClient looks like:

```java
@FeignClient("cat-service")
public interface CatClient {

  @GetMapping("/api/v1/cats")
  List<Cat> getAllCats();
}
```
This produces an error:

```
[dog-service-b97b7f566-lgn6s dog-service] com.netflix.client.ClientException: Load balancer does not have available server for client: cat-service
[dog-service-b97b7f566-lgn6s dog-service] 	at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
[dog-service-b97b7f566-lgn6s dog-service] 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
[dog-service-b97b7f566-lgn6s dog-service] 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.Subscriber.setProducer(Subscriber.java:209) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.Observable.subscribe(Observable.java:10423) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.Observable.subscribe(Observable.java:10390) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.observables.BlockingObservable.single(BlockingObservable.java:340) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]
[dog-service-b97b7f566-lgn6s dog-service] 	at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:83) ~[spring-cloud-openfeign-core-2.2.3.RELEASE.jar:2.2.3.RELEASE]
[dog-service-b97b7f566-lgn6s dog-service] 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119) ~[feign-core-10.10.1.jar:na]
[dog-service-b97b7f566-lgn6s dog-service] 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[feign-core-10.10.1.jar:na]
[dog-service-b97b7f566-lgn6s dog-service] 	at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:109) ~[feign-hystrix-10.10.1.jar:na]
[dog-service-b97b7f566-lgn6s dog-service] 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302) ~[hystrix-core-1.5.18.jar:1.5.18]
[dog-service-b97b7f566-lgn6s dog-service] 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298) ~[hystrix-core-1.5.18.jar:1.5.18]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) ~[hystrix-core-1.5.18.jar:1.5.18]
[dog-service-b97b7f566-lgn6s dog-service] 	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) ~[hystrix-core-1.5.18.jar:1.5.18]
[dog-service-b97b7f566-lgn6s dog-service] 	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) ~[hystrix-core-1.5.18.jar:1.5.18]
[dog-service-b97b7f566-lgn6s dog-service] 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[rxjava-1.3.8.jar:1.3.8]
[dog-service-b97b7f566-lgn6s dog-service] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
[dog-service-b97b7f566-lgn6s dog-service] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
[dog-service-b97b7f566-lgn6s dog-service] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
[dog-service-b97b7f566-lgn6s dog-service] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
[dog-service-b97b7f566-lgn6s dog-service] 	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by spencergibb** [comment]
pretty sure that's because of the missing moudle. Going back to 1.1.1 should fix that (or the upcoming 1.1.4 release).

See also #516

**Comment by Alos** [comment]
Thanks @spencergibb! Based on what @ryanjbaxter mentioned, I think eventually we will not be able to use `spring-cloud-kubernetes-ribbon` so I'm kinda trying to understand how this would work on the next major version. Should I be using `spring-cloud-starter-loadbalancer` instead?

**Comment by spencergibb** [comment]
yes, hence the mention of #516

**Comment by Alos** [comment]
Replacing the ribbon implementation with:

```
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-loadbalancer</artifactId>
    </dependency>
```

Threw a different exception:

```
[dog-service-5c768784c8-mwc4d dog-service] feign.FeignException$ServiceUnavailable: [503] during [GET] to [http://cat-service/api/v1/cats] [CatClient#getAllCats()]: [Load balancer does not contain an instance for the service cat-service]
```

My guess is that the URL is missing the 8080 port, is there a way to configure this?

**Comment by piomin** [comment]
That's probably , because sprrng-cloud-openfeign does not support spring-cloud-load-balancer - https://github.com/spring-cloud/spring-cloud-openfeign/issues/342

**Comment by Alos** [comment]
Bumped to:

```xml
<dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-openfeign</artifactId>
      <version>3.0.0-SNAPSHOT</version>
</dependency>
```

Still getting:

```
[dog-service-666b69747b-xkfjp dog-service] 2020-06-24 22:25:18.511  WARN 1 --- [nio-8080-exec-1] .s.c.o.l.FeignBlockingLoadBalancerClient : Load balancer does not contain an instance for the service cat-service
[dog-service-666b69747b-xkfjp dog-service] 2020-06-24 22:25:18.541 ERROR 1 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is feign.FeignException$ServiceUnavailable: [503] during [GET] to [http://cat-service/api/v1/cats] [CatClient#getAllCats()]: [Load balancer does not contain an instance for the service cat-service]] with root cause
[dog-service-666b69747b-xkfjp dog-service] 
[dog-service-666b69747b-xkfjp dog-service] feign.FeignException$ServiceUnavailable: [503] during [GET] to [http://cat-service/api/v1/cats] [CatClient#getAllCats()]: [Load balancer does not contain an instance for the service cat-service]
```

**Comment by piomin** [comment]
@Alos Take a look on my PR to your code: https://github.com/Alos/K8sFeignClientExample/pull/1.
I added there a test that shows that it works. However, I had to add the dependencies you see below and also disable ribbon using property spring.cloud.loadbalancer.ribbon.enabled: false.

```

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-kubernetes-all</artifactId>
      <version>2.0.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-loadbalancer</artifactId>
      <version>3.0.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-openfeign</artifactId>
      <version>3.0.0-SNAPSHOT</version>
    </dependency>
```

**Comment by Alos** [comment]
I pulled in the changes, cleaned and rebuild and redeployed. It looks like I get the same error. :(

**Comment by Alos** [comment]
I added:

```
logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG
``` 

I think I see an issue with the RBAC permissions, let me see if this fixes the problem

**Comment by Alos** [comment]
Aha! Fixing the permissions did make the sample app work now! Thanks for all the help @piomin. Also thanks for pointing me to:

```
<dependency>
    <groupId>io.fabric8</groupId>
    <artifactId>kubernetes-server-mock</artifactId>
    <scope>test</scope>
</dependency>
```

**Comment by Alos** [comment]
Ah it looks like the SNAPSHOT version broke; @piomin is it common to report this as a bug?

```
dog-service: Could not resolve dependencies for project com.example:dog-service:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.springframework.cloud:spring-cloud-starter-kubernetes-all:jar:2.0.0-SNAPSHOT: Failed to read artifact descriptor for org.springframework.cloud:spring-cloud-starter-kubernetes-all:jar:2.0.0-SNAPSHOT: Could not find artifact io.projectreactor:reactor-bom:pom:2020.0.0-M1 in spring-snapshots (https://repo.spring.io/snapshot)```

**Comment by spencergibb** [comment]
you need the milestone repo as well.

**Comment by Alos** [comment]
It looks like I get an authorization error now:

```
Authorization failed for http://repo.spring.io/milestone/io/projectreactor/reactor-bom/2020.0.0-M1/reactor-bom-2020.0.0-M1.pom 403 Forbidden
```

I'm not sure if its something I broke in my Maven settings :(

**Comment by spencergibb** [comment]
That link works for me

**Comment by Alos** [comment]
I get a:

```HTTP is not supported. Please use HTTPS```

**Comment by spencergibb** [comment]
My browser redirected. Change to https

**Comment by Alos** [comment]
Right but Maven won't know how to redirect to https, now looking to update Maven to latest version to see if it fixes the issue.

**Comment by spencergibb** [comment]
No, you have to change the url in your project to https

**Comment by Alos** [comment]
Of corse, I'm an idiot

**Comment by Alos** [comment]
I've added `spring-cloud-starter-circuitbreaker-resilience4j` to the FignClients in the DogService as an example and got everything working 👍
