### ISSUE TITLE
ConfigMap and Secret reload does not work if mounted

### ISSUE THREAD

**Issue by deepred-dev** [spring-cloud/spring-cloud-kubernetes#579]
Even with the latest Version 1.1.4.RELEASE automatic reload of configMaps and secrets still does not work if both are mounted and not accessed via API.

As already described for configMaps in the (automatically ?) closed issue  [#524](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/524)

In my bootstrap.properties I have disabled all access to the API and specified the path to the mounted configMaps and secrets:

```
spring.cloud.kubernetes.config.enabled=true
spring.cloud.kubernetes.config.enableApi=false
spring.cloud.kubernetes.config.paths=/opt/spring-boot/config/properties/common.properties,/opt/spring-boot/config/properties/appspecific.properties

spring.cloud.kubernetes.secrets.enabled=true
spring.cloud.kubernetes.secrets.enableApi=false
spring.cloud.kubernetes.secrets.paths=/opt/spring-boot/config/secrets

spring.cloud.kubernetes.reload.enabled=true
spring.cloud.kubernetes.reload.monitoring-config-maps=true
spring.cloud.kubernetes.reload.monitoring-secrets=false
```

The configMaps and secrets are mounted into the pods on Openshift 4.2 :

```
     volumes:
        - name: log4jconfig-volume
          configMap:
            name: log4jconfig
        - name: secrets-volume
          projected:
            sources:
              - secret:
                  name: commonsecrets
              - secret:
                  name: appsecrets
        - name: properties-volume
          projected:
            sources:
              - configMap:
                  name: common
              - configMap:
                  name: appspecific

          volumeMounts:
            - name: log4jconfig-volume
              mountPath: /opt/spring-boot/config/logging
              readOnly: true
            - name: secrets-volume
              mountPath: /opt/spring-boot/config/secrets
              readOnly: true
            - name: properties-volume
              mountPath: /opt/spring-boot/config/properties
              readOnly: true
```
All configMaps and secrets are successfully loaded, but then it complains, that " The current number of Confimap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place"

```
b.c.PropertySourceBootstrapConfiguration : [::] Located property source: [BootstrapPropertySource {name='bootstrapProperties-appspecific.properties'}, BootstrapPropertySource {name='bootstrapProperties-common.properties'}]
b.c.PropertySourceBootstrapConfiguration : [::] Located property source: [BootstrapPropertySource {name='bootstrapProperties-commonsecrets.properties'}, BootstrapPropertySource {name='bootstrapProperties-secretpwd'}, BootstrapPropertySource {name='bootstrapProperties-secretusername'}, BootstrapPropertySource {name='bootstrapProperties-commonsecretpwd'}, BootstrapPropertySource {name='bootstrapProperties-commonsecretusername'}]
INFO 1 --- [           main] .r.EventBasedConfigurationChangeDetector : [::] Added new Kubernetes watch: config-maps-watch
INFO 1 --- [           main] .r.EventBasedConfigurationChangeDetector : [::] Kubernetes event-based configuration change detector activated
WARN 1 r.EventBasedConfigurationChangeDetector : [::] The current number of Confimap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place
WARN 1 r.EventBasedConfigurationChangeDetector : [::] The current number of Confimap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place
WARN 1 r.EventBasedConfigurationChangeDetector : [::] The current number of Confimap PropertySources does not match the ones loaded from the Kubernetes - No reload will take place
```

Furthermore, if I enable `spring.cloud.kubernetes.reload.monitoring-secrets=true` it results in a stacktrace as it lacks the permission to watch the secret via API.  But as I disabled the API access for secrets, it should not use the API at all : `spring.cloud.kubernetes.secrets.enableApi=false`

```
WARN 1 ---  i.f.k.c.d.i.WatchConnectionManager       : [::] Exec Failure: HTTP 403, Status: 403 - secrets is forbidden: User "system:serviceaccount:springk8s-test:default" cannot watch resource "secrets" in API group "" in the namespace "springk8s-test"

java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess(RealWebSocket.java:224) [okhttp-3.14.9.jar!/:?]
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:195) [okhttp-3.14.9.jar!/:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) [okhttp-3.14.9.jar!/:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.14.9.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]

ERROR 1 --- [           main] .r.EventBasedConfigurationChangeDetector : [::] Error while establishing a connection to watch secrets: configuration may remain stale

io.fabric8.kubernetes.client.KubernetesClientException: secrets is forbidden: User "system:serviceaccount:springk8s-test:default" cannot watch resource "secrets" in API group "" in the namespace "springk8s-test"
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:203) ~[kubernetes-client-4.4.1.jar!/:?]
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570) ~[okhttp-3.14.9.jar!/:?]
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:199) ~[okhttp-3.14.9.jar!/:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) ~[okhttp-3.14.9.jar!/:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.14.9.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) ~[?:?]

Exception in thread "OkHttp Dispatcher" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@52b4563f[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@44e19340[Wrapped task = io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2@4ee9dbdc]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@564ddb01[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:715)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:714)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.scheduleReconnect(WatchConnectionManager.java:305)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.access$800(WatchConnectionManager.java:48)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:218)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:199)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

As manually shadowing the dependencies to force the usage of 1.1.4.RELEASE didn't change anything , I switched back to Hoxton.SR6 which of cause uses  1.1.3.RELEASE instead. 

But reloading the properties on change is not working for configMap nor secrets if disabeling API access and using mount instead.

**Comment by easymammoth** [comment]
I'm facing the same issue and tried Hoxton.SR7 / 1.1.5.RELEASE, but got the same error.

Any hope for a fix ? Or any solution to have reload working with mounted configmaps and secrets ?

**Comment by mclouvem** [comment]
I'm also facing same issue using version 1.1.6.RELEASE.

Is there any idea about when this issue will be resolved?

**Comment by ryanjbaxter** [comment]
There is no mechanism to reload configuration automatically when configmaps and secrets are mounted in the container.  We need to update the documentation to specify that.  There is a new [controller in master](https://docs.spring.io/spring-cloud-kubernetes/docs/2.0.0-M3/reference/html/#spring-cloud-kubernetes-configuration-watcher) that you can deploy that enables this functionality.
