### ISSUE TITLE
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Endpoints]  with name: [null]  in namespace: [null]  failed.

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-kubernetes#670]
**Describe the bug**
Spring Cloud version: Hoxton SR8
SpringBoot 2.3.5
Spring Boot admin 2.3.0

Wen starting a Spring Boot Admin server, I am encountering:
```
[   scheduling-1] o.s.c.k.d.KubernetesCatalogWatch         : Error watching Kubernetes Services

io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Endpoints]  with name: [null]  in namespace: [null]  failed.
[...]
Caused by: java.net.ConnectException: Failed to connect to /1xx.1xx.0.1:443
[...]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
```

**Sample**
```
  <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-kubernetes</artifactId>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-server</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-server-cloud</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-server-ui</artifactId>
            <version>2.3.0</version>
        </dependency>
```

```
@EnableScheduling
@EnableAdminServer
@EnableConfigServer
@EnableDiscoveryClient
@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class);
    }

}

```

What is he trying to connect to please?
Why am I getting this error please?

Thank you

**Comment by ryanjbaxter** [comment]
If you can reproduce the issue with Spring Admin please reopen this issue and provide a sample.

**Comment by patpatpat123** [comment]
Hello Ryan,

Thank you for the answer.
I am quite unsure why this issue is being closed.
Are you saying you believe this is a Spring Boot Admin issue and not a Spring Cloud Kubernetes issue, hence the close?
Thank you @ryanjbaxter

**Comment by ryanjbaxter** [comment]
Possibly, if you can reproduce the problem without using Spring Boot Admin and can provide a sample that demonstrates the problem please reopen the issue and attach the sample.

**Comment by vyom-soft** [comment]
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Endpoints]  with name: [null]  in namespace: [e-my-namespace]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:170)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:640)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:79)
	at org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatch.catalogServicesWatch(KubernetesCatalogWatch.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: timeout

**Comment by ryanjbaxter** [comment]
Just providing a stacktrace is not very useful

**Comment by himanshunetent** [comment]
@ryanjbaxter I also faced this issue, It seems the Spring Kubernetes trying to access port 443 which is not available. Is there a way to change the port number and use 8080 instead

**Comment by ryanjbaxter** [comment]
https://github.com/spring-cloud/spring-cloud-kubernetes/issues/670#issuecomment-736136770

**Comment by himanshunetent** [comment]
Hi @ryanjbaxter Just FYI I got this issue resolved by providing primary-port-name in my app service label. ))
Thanks

**Comment by alextodorovic-luma** [comment]
@himanshunetent could you specify how you did this? Having the same issue, not sure what needs to be done to try your solution.
