### ISSUE TITLE
spring-cloud-kubernetes-fabric8-leader: 2.0.1 - Watcher stopped unexpectedly, will restart 

### ISSUE THREAD

**Issue by whgibbo** [spring-cloud/spring-cloud-kubernetes#730]
Hi,
Using the **spring-cloud-kubernetes-fabric8-leader: 2.0.1** to determine a leader for the services in my pod.

Noticed the following warnings appearing:
```batch
021-02-05 12:19:23,429 WARN  [] [OkHttp https://172.20.0.1/...] o.s.c.k.f.l.Fabric8PodReadinessWatcher.onClose 104: Watcher stopped unexpectedly, will restart
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 58642569 (58743275)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:257)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

From what I've seen in another post, in the past it would attempt an reconnect but it has been reverted.
I believe this is the suggesting going forward [#1800 (comment)](https://github.com/fabric8io/kubernetes-client/pull/1800#issuecomment-549561724) .

Any plans to incorporate this ?
If not any suggestions on how to address this in the meantime..

Thanks

**Comment by ryanjbaxter** [comment]
There are a couple of related PRs related to retying failed requests related to configmaps and secrets
https://github.com/spring-cloud/spring-cloud-kubernetes/pull/648
https://github.com/spring-cloud/spring-cloud-kubernetes/pull/570

Both of them have kind of stalled out.

That said I am not entirely sure it would solve this specific problem as the exception seems to be coming from Fabric8, so it seems like the problem might be solved in Fabric8.

**Comment by whgibbo** [comment]
@ryanjbaxter  Thanks for the information..  In the meantime would changing the Fabrio8io back to an earlier version cause any issues?

**Comment by ryanjbaxter** [comment]
Hard to say.  I know I just updated the version and had to make some small tweaks because method signatures changed, but I am unsure if that would impact you.

I am going to close this issue for now in favor of the other issues that are already open.
