### ISSUE TITLE
GKE with Workload Identity enabled not working

### ISSUE THREAD

**Issue by Miles-Ahead-Digital** [spring-cloud/spring-cloud-kubernetes#759]
### **Describe the bug**
I run a private GKE Cluster with workload identity enabled.

The Spring Boot Application is not started due to this error:
```
io.fabric8.kubernetes.client.KubernetesClientException: 
Failure executing: GET at: https://10.232.0.1/api/v1/namespaces/miles-ahead-dev/configmaps/frontend. 
Message: Forbidden!Configured service account doesn't have access. 
Service account may have been revoked. configmaps "frontend" is forbidden: 
User "system:serviceaccount:miles-ahead-dev:default" cannot get resource "configmaps" in API group "" 
in the namespace "miles-ahead-dev".
```

### **My Customizing:**

The Application run in Namespace miles-ahead-dev
In this Namespace there is a default serviceaccount:
```
k describe serviceaccounts default -n miles-ahead-dev
Name:                default
Namespace:           miles-ahead-dev
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   default-token-krqlh
Tokens:              default-token-krqlh
Events:              <none>

```

I added this account to my IAM service account sa-node-prd-k8s@prd-k8s-cluster.iam.gserviceaccount.com which has Owner rights
```
 gcloud iam service-accounts add-iam-policy-binding sa-node-prd-k8s@prd-k8s-cluster.iam.gserviceaccount.com \
    --member="serviceAccount:prd-k8s-cluster.svc.id.goog[miles-ahead-dev/default]" \
    --role=roles/iam.workloadIdentityUser --project=prd-k8s-cluster
```

### **Complete Stacktrace:**
```
2021-03-15 09:13:37.825  WARN 1 --- [  restartedMain] s.c.k.f.c.Fabric8ConfigMapPropertySource : Can't read configMap with name: [frontend] in namespace:[miles-ahead-dev]. Ignoring.

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.232.0.1/api/v1/namespaces/miles-ahead-dev/configmaps/frontend. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. configmaps "frontend" is forbidden: User "system:serviceaccount:miles-ahead-dev:default" cannot get resource "configmaps" in API group "" in the namespace "miles-ahead-dev".
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:589) ~[kubernetes-client-4.10.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:526) ~[kubernetes-client-4.10.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:492) ~[kubernetes-client-4.10.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:451) ~[kubernetes-client-4.10.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:416) ~[kubernetes-client-4.10.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:397) ~[kubernetes-client-4.10.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:890) ~[kubernetes-client-4.10.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:233) ~[kubernetes-client-4.10.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:187) ~[kubernetes-client-4.10.3.jar:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:79) ~[kubernetes-client-4.10.3.jar:na]
        at org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySource.getData(Fabric8ConfigMapPropertySource.java:62) ~[spring-cloud-kubernetes-fabric8-config-2.0.1.jar:2.0.1]
        at org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySource.<init>(Fabric8ConfigMapPropertySource.java:50) ~[spring-cloud-kubernetes-fabric8-config-2.0.1.jar:2.0.1]
        at org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySourceLocator.getMapPropertySource(Fabric8ConfigMapPropertySourceLocator.java:51) ~[spring-cloud-kubernetes-fabric8-config-2.0.1.jar:2.0.1]
        at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.getMapPropertySourceForSingleConfigMap(ConfigMapPropertySourceLocator.java:81) ~[spring-cloud-kubernetes-commons-2.0.1.jar:2.0.1]
        at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.lambda$locate$0(ConfigMapPropertySourceLocator.java:67) ~[spring-cloud-kubernetes-commons-2.0.1.jar:2.0.1]
        at java.base/java.util.Collections$SingletonList.forEach(Collections.java:4856) ~[na:na]
        at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.locate(ConfigMapPropertySourceLocator.java:67) ~[spring-cloud-kubernetes-commons-2.0.1.jar:2.0.1]
        at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51) ~[spring-cloud-context-3.0.1.jar:3.0.1]
        at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47) ~[spring-cloud-context-3.0.1.jar:3.0.1]
        at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95) ~[spring-cloud-context-3.0.1.jar:3.0.1]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:635) ~[spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:390) ~[spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) ~[spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.4.3.jar:2.4.3]
        at milesahead.aal.frontend.FrontendApplication.main(FrontendApplication.java:44) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.4.3.jar:2.4.3]

```

PLEASE ADVISE!

**Comment by Miles-Ahead-Digital** [comment]
I added the config below. But I'm getting a differnt error now.
I will close this ticket and open a new one for the new error.

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: miles-ahead-dev
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: miles-ahead-dev
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
