### ISSUE TITLE
NoClassDefFoundError for BootstrapPropertySource during container init

### ISSUE THREAD

**Issue by amit4aws** [spring-cloud/spring-cloud-kubernetes#774]
I am following the example on Config reload. My dependencies look like this :- 

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-fabric8-config</artifactId>
    <version>2.0.0</version>
</dependency>

	<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-actuator-autoconfigure</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

Rest everything remains same as per the reload example. Now when run the pod, In the logs i am seeing the following error :: 

2021-04-08 10:29:08.905 DEBUG 1 --- [   scheduling-1] c.k.c.c.r.PollingConfigMapChangeDetector : Polling for changes in config maps
2021-04-08 10:29:08.905 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.NoClassDefFoundError: org/springframework/cloud/bootstrap/config/BootstrapPropertySource
        at org.springframework.cloud.kubernetes.commons.config.reload.ConfigurationChangeDetector.findPropertySources(ConfigurationChangeDetector.java:135)
        at org.springframework.cloud.kubernetes.commons.config.reload.PollingConfigMapChangeDetector.executeCycle(PollingConfigMapChangeDetector.java:69)
        at jdk.internal.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

The first message is: a message that can be changed live
The other message is: this is a dummy message

**Comment by amit4aws** [comment]
Never mind. I was able to figure out the issue.
