### ISSUE TITLE
discovery.service-labels not works with spring-cloud-starter-kubernetes-client v2.0.1

### ISSUE THREAD

**Issue by uqix** [spring-cloud/spring-cloud-kubernetes#810]
**Describe the bug**
`spring.cloud.kubernetes.discovery.service-labels` is ignored with spring-cloud-starter-kubernetes-client v2.0.1, and `ServiceInstance` metadata contains null key(`null=8080`) if the k8s service/deployment doesn't have named ports, which causes NPE from downstream like spring boot admin `Tags`.

**Comment by edwardzjl** [comment]
I think I'm running into the same issue with spring-cloud-starter-kubernetes-client v2.0.3

I have 3 services, and only 1 of them is labeled as "openapi-service":

![svc](https://user-images.githubusercontent.com/7287580/127482510-6295ce97-b293-4628-b9d4-4ccd7c34610a.png)

when I set service-labels to only select service with "openapi-service" label: ( or openapi-service=true, same effect )

![config](https://user-images.githubusercontent.com/7287580/127482852-fd2ffda1-f0ef-4573-ba48-01cc4c50363e.png)

The pod cannot start, with no ERROR information
container log shows it's applying a service without "openapi-service" label, twice:

![error](https://user-images.githubusercontent.com/7287580/127483170-5bd5c44b-c7fe-4e5a-b219-8fe93c645e80.png)

And that's the end of log, the container exists after that.

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by andrein** [comment]
I've attached a somewhat-minimal example using [spring-boot-admin](https://github.com/spring-cloud/spring-cloud-kubernetes/files/6919441/spring-boot-admin.zip)

There are two (separate?) issues here:

1) `spring.cloud.kubernetes.discovery.service-labels` seems to be ignored, spring-boot-admin detects every service in the namespace
2) if one of the detected services doesn't have named ports, discovery crashes with with a NPE (this looks like a bug in spring-boot-admin):
```
java.lang.NullPointerException: null
        at de.codecentric.boot.admin.server.domain.values.Tags.lambda$from$0(Tags.java:81) ~[spring-boot-admin-server-2.4.3.jar:2.4.3]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[na:na]
        at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Unknown Source) ~[na:na]
        at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[na:na]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[na:na]
        at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~[na:na]
        at de.codecentric.boot.admin.server.domain.values.Tags.from(Tags.java:82) ~[spring-boot-admin-server-2.4.3.jar:2.4.3]
        at de.codecentric.boot.admin.server.domain.entities.Instance.lambda$updateTags$1(Instance.java:270) ~[spring-boot-admin-server-2.4.3.jar:2.4.3]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:na]
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.reduce(Unknown Source) ~[na:na]
        at de.codecentric.boot.admin.server.domain.entities.Instance.updateTags(Instance.java:270) ~[spring-boot-admin-server-2.4.3.jar:2.4.3]
        at de.codecentric.boot.admin.server.domain.entities.Instance.apply(Instance.java:208) ~[spring-boot-admin-server-2.4.3.jar:2.4.3]
        at de.codecentric.boot.admin.server.domain.entities.Instance.register(Instance.java:120) ~[spring-boot-admin-server-2.4.3.jar:2.4.3]
        at de.codecentric.boot.admin.server.services.InstanceRegistry.lambda$register$0(InstanceRegistry.java:57) ~[spring-boot-admin-server-2.4.3.jar:2.4.3]
        at de.codecentric.boot.admin.server.domain.entities.EventsourcingInstanceRepository.lambda$compute$6(EventsourcingInstanceRepository.java:76) ~[spring-boot-admin-server-2.4.3.jar:2.4.3]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4338) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:181) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4323) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainSync(FluxFlattenIterable.java:604) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:683) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.request(FluxFlattenIterable.java:274) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:191) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:87) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onSubscribe(FluxFlattenIterable.java:216) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:87) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:160) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4338) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.Mono.subscribeWith(Mono.java:4453) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4309) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4245) ~[reactor-core-3.4.8.jar:3.4.8]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4217) ~[reactor-core-3.4.8.jar:3.4.8]
        at de.codecentric.boot.admin.server.cloud.discovery.InstanceDiscoveryListener.discover(InstanceDiscoveryListener.java:129) ~[spring-boot-admin-server-cloud-2.4.3.jar:2.4.3]
        at de.codecentric.boot.admin.server.cloud.discovery.InstanceDiscoveryListener.onApplicationReady(InstanceDiscoveryListener.java:100) ~[spring-boot-admin-server-cloud-2.4.3.jar:2.4.3]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.9.jar:5.3.9]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.9.jar:5.3.9]
        at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.9.jar:5.3.9]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.9.jar:5.3.9]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.9.jar:5.3.9]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.9.jar:5.3.9]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.9.jar:5.3.9]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.9.jar:5.3.9]
        at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111) ~[spring-boot-2.5.3.jar:2.5.3]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79) ~[spring-boot-2.5.3.jar:2.5.3]
        at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.3.jar:2.5.3]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.3.jar:2.5.3]
        at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79) ~[spring-boot-2.5.3.jar:2.5.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:353) ~[spring-boot-2.5.3.jar:2.5.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.3.jar:2.5.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.3.jar:2.5.3]
        at net.smartx.springbootadmin.SpringBootAdminApplication.main(SpringBootAdminApplication.java:18) ~[classes/:na]
```

**Comment by ryanjbaxter** [comment]
Can you provide a sample without Spring Boot Admin?  that can complicate things.

**Comment by andrein** [comment]
@ryanjbaxter  [here it is](https://github.com/spring-cloud/spring-cloud-kubernetes/files/6922504/demo.zip), the app is configured to discover services with the `spring-boot=true` label, but it discovers every service in the current namespace.

**Comment by ryanjbaxter** [comment]
Possibly yes, I am on vacation for the next week, so I will look at it when I get back

**Comment by ryanjbaxter** [comment]
Please provide a way to build the image and the deplyment and service yaml to deploy it to k8s

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by edwardzjl** [comment]
@ryanjbaxter Hi, I created a [repository](https://github.com/edwardzjl/spring-cloud-kubernetes-discovery-demo) based on @andrein 's demo code, with a docker file and a deploy yaml file.
