### ISSUE TITLE
spring.cloud.kubernetes.enabled=false is not read from bootstrap.yml in bootstrap run of `AbstractKubernetesProfileEnvironmentPostProcessor`

### ISSUE THREAD

**Issue by pandrez** [spring-cloud/spring-cloud-kubernetes#819]
Context:
Spring Boot 2.5.1
Spring Cloud 2020.0.3
Using `spring-cloud-starter-kubernetes-fabric8`

When starting an application with `spring.cloud.kubernetes.enabled=false` defined on `bootstrap.properties`, this flag is not added to the environment and it causes the application to create a `DefaultKubernetesClient` instance which will try to interact with a K8s cluster.
This can be seen debugging the supplied example application with a breakpoint on `AbstractKubernetesProfileEnvironmentPostProcessor` line 61.

In my case, I have a k8s config file with a defined cluster that uses OIDC authentication. When I run the supplied  application, even though I disabled spring.cloud.kubernetes, the application opens a browser to start the authentication process and hangs the startup.

Application: https://github.com/pandrez/spring-cloud-kubernetes

If you need more information, please let me know

**Comment by wind57** [comment]
I am a tiny bit confused, can you explain please where `DefaultKubernetesClient` would be created and why? thank you.

**Comment by pandrez** [comment]
Sure!
Since `kubernetesEnabled` is false on line 61 on `AbstractKubernetesProfileEnvironmentPostProcessor`, the method `addKubernetesProfileIfMissing` is called. Inside this method, `isInsideKubernetes` is called as part of the `if` condition.

The `isInsideKubernetes` method is an abstract method which is overridden on `Fabric8ProfileEnvironmentPostProcessor` where the `DefaultKubernetesClient` is created.

**Comment by wind57** [comment]
right. but : "Since kubernetesEnabled is false..." means that:


```
if (!kubernetesEnabled) {
     return;
}
```

which means that the method `addKubernetesProfileIfMissing` is _not_ going to be invoked? 

You probably did not set `spring.cloud.kubernetes.enabled=false` correctly? I might need to look at your application...

**Comment by pandrez** [comment]
> right. but : "Since kubernetesEnabled is false..." means that:
> 
> ```
> if (!kubernetesEnabled) {
>      return;
> }
> ```
> 
> which means that the method `addKubernetesProfileIfMissing` is _not_ going to be invoked? (at least I am looking in the `main` branch currently)
> 
> You probably did not set `spring.cloud.kubernetes.enabled=false` correctly? I might need to look at your application...

Sorry! Wrong spelling!
I meant `kubernetesEnabled` is true. I have already edited my previous response! Sorry about that!

In the supplied example, I believe I have setted everything correctly!

**Comment by wind57** [comment]
how can it be `true` if in your initial post you say : "spring.cloud.kubernetes.enabled=false"? So you never disabled it?  It's getting really confusing.

**Comment by pandrez** [comment]
Please take a look at the provided sample application. It is really simple and the problem is easily reproducible! If you look at `bootstrap.properties` you will see that `spring.cloud.kubernetes.enabled` is `false` but if you place a breakpoint on `AbstractKubernetesProfileEnvironmentPostProcessor` line 61 you will see that `spring.cloud.kubernetes.enabled` is `true`

**Comment by wind57** [comment]
you are using a recent version of `spring-boot`, as such read this: https://stackoverflow.com/questions/65063402/why-bootstrap-properties-is-ignored-by-spring-cloud-starter-config

**Comment by wind57** [comment]
I had more time to look at the problem you reported today and yes, I agree this is a bug. At least imo. The solution in your case is trivial, just start the application with an environment property, for example `-DSPRING_CLOUD_KUBERNETES_ENABLED=false`.

As to an actual fix, I will propose a PR and a fix this week, let's see what leads of the project think about it.

**Comment by pandrez** [comment]
> I had more time to look at the problem you reported today and yes, I agree this is a bug. At least imo. The solution in your case is trivial, just start the application with an environment property, for example `-DSPRING_CLOUD_KUBERNETES_ENABLED=false`.
> 
> I'll see if I can come up with a fix

Thank you @wind57!!

**Comment by wind57** [comment]
This one is interesting. 

According to [this](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1223), `AbstractKubernetesProfileEnvironmentPostProcessor::postProcessEnvironment` is called twice (or any `EnvironmentPostProcessor`). This is indeed the case when I take your application and run it. 

It seems that the first invocation is triggered by the bootstrap infrastructure itself(I did not look at the exact details here), where that `spring.cloud.kubernetes.enabled` property is not yet present.

The second invocation is done because we added :

```
org.springframework.boot.env.EnvironmentPostProcessor=\
org.springframework.cloud.kubernetes.fabric8.profile.Fabric8ProfileEnvironmentPostProcessor
```

in `spring.factories`. This invocation, correctly sees that `spring.cloud.kubernetes.enabled=false`.

So we could just have a `volatile boolean called` inside `AbstractKubernetesProfileEnvironmentPostProcessor`, but this relies on implementation details; which I am not sure team members here would like.

I would appreciate an advice/hint from @ryanjbaxter or @spencergibb . There might be another solution that I do not see.

**Comment by spencergibb** [comment]
I believe the bug is in the value of `Ordered` in `AbstractKubernetesProfileEnvironmentPostProcessor`.

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/6f9e9bc68efbf9da4398aca51a601bca4857af12/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/profile/AbstractKubernetesProfileEnvironmentPostProcessor.java#L48-L49

The comment on the order is so it can be available for `ConfigDataEnvironmentPostProcessor`, but that is the thing that loads bootstrap.properties, so that is why the value isn't available. 

There is a chicken and egg problem here. If you want the profile added before config data is run, the value can't be in bootstrap.properties. If you want the value to be read from bootstrap.properties, it's too late to add the profile.

Disabling via a system property, env var or cli prop is the only way to disable the post processor. This should be documented as there is no way around this that I can see.

**Comment by wind57** [comment]
@spencergibb if all we want is the profile to be added, then why not:


```
        private static boolean skip = false;

	@Override
	public void postProcessEnvironment(ConfigurableEnvironment environment, SpringApplication application) {

		if (PropertyUtils.bootstrapEnabled(environment) || PropertyUtils.useLegacyProcessing(environment)) {
			if (!skip) {
				addKubernetesProfileIfMissing(environment);
				skip = true;
				return;
			}
		}

		application.addInitializers(ctx -> LOG.replayTo(AbstractKubernetesProfileEnvironmentPostProcessor.class));

		boolean kubernetesEnabled = environment.getProperty("spring.cloud.kubernetes.enabled", Boolean.class, true);
		if (!kubernetesEnabled) {
			return;
		}
		addNamespaceFromServiceAccountFile(environment);

	}
```

**Comment by spencergibb** [comment]
How would the user disable adding the profile in bootstrap, which is a totally valid place to have the profile?

**Comment by wind57** [comment]
nvm, you're right. I have realized that after posting, thus deleted after. my bad!

**Comment by wind57** [comment]
will [this](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/820/files) work for a documentation change?

**Comment by limkinZero** [comment]
I'm trying to disable kubernetes in my local profile in `application.properties` setting 
```properties
spring.cloud.kubernetes.enabled=false
```
but no effect. Always try to check the configmaps.

```logs
2021-06-30T12:47:02,060 INFO  [restartedMain] c.u.j.EncryptablePropertySourceConverter: Converting PropertySource configurationProperties [org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource] to AOP Proxy
2021-06-30T12:47:02,060 INFO  [restartedMain] c.u.j.EncryptablePropertySourceConverter: Converting PropertySource bootstrap [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2021-06-30T12:47:02,060 INFO  [restartedMain] c.u.j.EncryptablePropertySourceConverter: Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2021-06-30T12:47:02,060 INFO  [restartedMain] c.u.j.EncryptablePropertySourceConverter: Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableMapPropertySourceWrapper
2021-06-30T12:47:02,060 INFO  [restartedMain] c.u.j.EncryptablePropertySourceConverter: Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2021-06-30T12:47:02,060 INFO  [restartedMain] c.u.j.EncryptablePropertySourceConverter: Converting PropertySource KUBERNETES_NAMESPACE_PROPERTY_SOURCE [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2021-06-30T12:47:02,060 INFO  [restartedMain] c.u.j.EncryptablePropertySourceConverter: Converting PropertySource springCloudClientHostInfo [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2021-06-30T12:47:02,060 INFO  [restartedMain] c.u.j.EncryptablePropertySourceConverter: Converting PropertySource devtools [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2021-06-30T12:47:02,060 INFO  [restartedMain] c.u.j.EncryptablePropertySourceConverter: Converting PropertySource defaultProperties [org.springframework.core.env.MapPropertySource] to EncryptableMapPropertySourceWrapper
2021-06-30T12:47:02,133 WARN  [restartedMain] o.s.c.k.f.Fabric8AutoConfiguration: No namespace has been detected. Please specify KUBERNETES_NAMESPACE env var, or use a later kubernetes version (1.3 or later)
....
2021-06-30T12:47:05,002 WARN  [restartedMain] o.s.c.k.f.c.Fabric8ConfigMapPropertySource: Can't read configMap with name: [awe-boot] in namespace:[null]. Ignoring.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [ConfigMap]  with name: [my-app]  in namespace: [null]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:244)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:187)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:79)
	at org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySource.getData(Fabric8ConfigMapPropertySource.java:61)
	at org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySource.<init>(Fabric8ConfigMapPropertySource.java:50)
	at org.springframework.cloud.kubernetes.fabric8.config.Fabric8ConfigMapPropertySourceLocator.getMapPropertySource(Fabric8ConfigMapPropertySourceLocator.java:51)
	at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.getMapPropertySourceForSingleConfigMap(ConfigMapPropertySourceLocator.java:81)
	at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.lambda$locate$0(ConfigMapPropertySourceLocator.java:67)
	at java.base/java.util.Collections$SingletonList.forEach(Collections.java:4854)
	at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.locate(ConfigMapPropertySourceLocator.java:67)
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51)
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:639)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:402)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318)
	at com.almis.awe.AppBootApplication.main(AppBootApplication.java:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.net.ConnectException: Failed to connect to kubernetes.docker.internal/127.0.0.1:6443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:134)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:149)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:490)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:451)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:416)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:397)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:890)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:233)
	... 23 more
Caused by: java.net.ConnectException: Connection refused: connect
```

**Comment by wind57** [comment]
@limkinZero can you open a separate issue to track this? this seems un-related to the original one.

**Comment by wind57** [comment]
@limkinZero I think I know where your issue comes from. You need to set that property in `bootstrap.yaml` as the reading of config maps happens at the bootstrap level, see [here](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8BootstrapConfiguration.java#L51).
