### ISSUE TITLE
Since 2.0.4, can not start outside of k8s

### ISSUE THREAD

**Issue by olivierboudet** [spring-cloud/spring-cloud-kubernetes#876]
**Describe the bug**
In version 2.0.3, the application can start outside of k8s (in intellij for example). There are some warnings at startup but there are not fatal.

Since 2.0.4, the application fails to start, even if the kubernetes profile is not activated.

```
2021-10-04 15:58:58.478  WARN 3506943 --- [           main] ubernetesProfileEnvironmentPostProcessor : Not running inside kubernetes. Skipping 'kubernetes' profile activation.
2021-10-04 15:58:58.650  INFO 3506943 --- [           main] o.s.c.k.client.KubernetesClientUtils     : Could not create the Kubernetes ApiClient in a cluster environment, because : 

java.lang.IllegalStateException: java.lang.NumberFormatException: null
	at io.kubernetes.client.util.ClientBuilder.setBasePath(ClientBuilder.java:248) ~[client-java-11.0.2.jar:na]
	at io.kubernetes.client.util.ClientBuilder.cluster(ClientBuilder.java:234) ~[client-java-11.0.2.jar:na]
	at org.springframework.cloud.kubernetes.client.KubernetesClientUtils.kubernetesApiClient(KubernetesClientUtils.java:37) ~[spring-cloud-kubernetes-client-autoconfig-2.0.4.jar:2.0.4]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration.apiClient(KubernetesClientAutoConfiguration.java:44) ~[spring-cloud-kubernetes-client-autoconfig-2.0.4.jar:2.0.4]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$79138be4.CGLIB$apiClient$0(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.0.4.jar:2.0.4]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$79138be4$$FastClassBySpringCGLIB$$bb22f31b.invoke(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.0.4.jar:2.0.4]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.10.jar:5.3.10]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$79138be4.apiClient(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.0.4.jar:2.0.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:143) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:197) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:77) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63) ~[spring-boot-2.5.5.jar:2.5.5]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:374) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:332) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.5.jar:2.5.5]
	at com.myproject.PassecoApplication.main(PassecoApplication.java:10) ~[main/:na]
Caused by: java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:614) ~[na:na]
	at java.base/java.lang.Integer.valueOf(Integer.java:983) ~[na:na]
	at io.kubernetes.client.util.ClientBuilder.setBasePath(ClientBuilder.java:244) ~[client-java-11.0.2.jar:na]
	... 48 common frames omitted

2021-10-04 15:58:58.651  INFO 3506943 --- [           main] o.s.c.k.client.KubernetesClientUtils     : Trying to use a "standard" configuration to create the Kubernetes ApiClient
2021-10-04 15:58:58.674  WARN 3506943 --- [           main] o.s.c.k.client.KubernetesClientUtils     : Could not create a Kubernetes ApiClient from either a cluster or standard environment. Will return one that always connects to localhost:8080

java.lang.IllegalStateException: Unimplemented
	at io.kubernetes.client.util.authenticators.GCPAuthenticator.refresh(GCPAuthenticator.java:61) ~[client-java-11.0.2.jar:na]
	at io.kubernetes.client.util.KubeConfig.getAccessToken(KubeConfig.java:215) ~[client-java-11.0.2.jar:na]
	at io.kubernetes.client.util.credentials.KubeconfigAuthentication.<init>(KubeconfigAuthentication.java:46) ~[client-java-11.0.2.jar:na]
	at io.kubernetes.client.util.ClientBuilder.kubeconfig(ClientBuilder.java:283) ~[client-java-11.0.2.jar:na]
	at io.kubernetes.client.util.ClientBuilder.getClientBuilder(ClientBuilder.java:115) ~[client-java-11.0.2.jar:na]
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:94) ~[client-java-11.0.2.jar:na]
	at io.kubernetes.client.util.ClientBuilder.standard(ClientBuilder.java:86) ~[client-java-11.0.2.jar:na]
	at io.kubernetes.client.util.ClientBuilder.defaultClient(ClientBuilder.java:68) ~[client-java-11.0.2.jar:na]
	at org.springframework.cloud.kubernetes.client.KubernetesClientUtils.kubernetesApiClient(KubernetesClientUtils.java:45) ~[spring-cloud-kubernetes-client-autoconfig-2.0.4.jar:2.0.4]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration.apiClient(KubernetesClientAutoConfiguration.java:44) ~[spring-cloud-kubernetes-client-autoconfig-2.0.4.jar:2.0.4]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$79138be4.CGLIB$apiClient$0(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.0.4.jar:2.0.4]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$79138be4$$FastClassBySpringCGLIB$$bb22f31b.invoke(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.0.4.jar:2.0.4]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.10.jar:5.3.10]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration$$EnhancerBySpringCGLIB$$79138be4.apiClient(<generated>) ~[spring-cloud-kubernetes-client-autoconfig-2.0.4.jar:2.0.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:143) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:197) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:77) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63) ~[spring-boot-2.5.5.jar:2.5.5]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:374) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:332) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.5.jar:2.5.5]
	at com.myproject.PassecoApplication.main(PassecoApplication.java:10) ~[main/:na]


  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.5)

2021-10-04 15:58:58.784 ERROR 3506943 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.cloud.kubernetes.commons.config.NamespaceResolutionFailedException: unresolved namespace
	at org.springframework.cloud.kubernetes.client.config.KubernetesClientConfigUtils.getApplicationNamespace(KubernetesClientConfigUtils.java:110) ~[spring-cloud-kubernetes-client-config-2.0.4.jar:2.0.4]
	at org.springframework.cloud.kubernetes.client.config.KubernetesClientConfigMapPropertySourceLocator.getMapPropertySource(KubernetesClientConfigMapPropertySourceLocator.java:86) ~[spring-cloud-kubernetes-client-config-2.0.4.jar:2.0.4]
	at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.getMapPropertySourceForSingleConfigMap(ConfigMapPropertySourceLocator.java:88) ~[spring-cloud-kubernetes-commons-2.0.4.jar:2.0.4]
	at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.lambda$locate$0(ConfigMapPropertySourceLocator.java:73) ~[spring-cloud-kubernetes-commons-2.0.4.jar:2.0.4]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.cloud.kubernetes.commons.config.ConfigMapPropertySourceLocator.locate(ConfigMapPropertySourceLocator.java:73) ~[spring-cloud-kubernetes-commons-2.0.4.jar:2.0.4]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95) ~[spring-cloud-context-3.0.4.jar:3.0.4]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:634) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:403) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.5.jar:2.5.5]
	at com.myproject.PassecoApplication.main(PassecoApplication.java:10) ~[main/:na]


Process finished with exit code 1

```

Is this expected ? It was much simplier to use spring-cloud-kubernetes in versions <2.0.3 without to have to set `spring.cloud.kubernetes.config.enabled` on each environment.

**Comment by wind57** [comment]
that is something that should not happen. I will take a look.

**Comment by wind57** [comment]
Yes, this is expected. You get a `org.springframework.cloud.kubernetes.commons.config.NamespaceResolutionFailedException: unresolved namespace`

The documentation has been updated, look [here](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#namespace-resolution).

You need to specify an explicit namespace from now on. There are good reasons why we have done that.

**Comment by jvalkeal** [comment]
I was just about to create same type of issue as this prevents us in `spring-cloud-dataflow` to upgrade to `2020.0.4`. We have same server which is run locally(no k8s or cloudfroundry), in cf or in k8s. It's difficult for use to disable needed settings and then ask users to re-enable as there's also bootstrap context involved.

I'd prefer to see that spring-cloud-kubernetes would not be so aggressive as it's perfectly valid use case for running outside of k8s without requiring specific options to be set.

**Comment by jvalkeal** [comment]
This is really a breaking change for a point release. It might not be a bad idea to either restore original behaviour not to fail fast or add some more magic like `@ConditionalOnKubernetes` which could try to see if we're actually on a cluster and then steps away if auto-config can't proceed.

**Comment by wind57** [comment]
Thank you both for the feedback, I actually added this. It seemed reasonable to add such functionality because there is no way to find a `namespace` in a precise way, we were always relying on somehow imprecise actions. The situation gets slightly worse because in kubernetes-client there is simply no way to even try to "guess" a correct namespace (unlike `fabric8`), so we actually had a nasty bug in disguise there, were we could expose wrong secrets. 

That being said, I think that enforcing such a check only when you are actually in a k8s cluster is something we can do and also seems like the correct way to handle this. I'll spend some time to think how to properly and transparently fix this.

**Comment by ar-bella-jeong** [comment]
I'm faced with the same problem. Although I set the property `spring.cloud.kubernetes.client.namespace` in application.yaml , the error was occured in local env. :( 
Is there other ways to pass the validation?

**Comment by wind57** [comment]
@olivierboudet @jvalkeal can I ask you to provide a bit of details on your set-up btw?

The only way to get that exception is if you have enabled:

```
spring:
  cloud:
    kubernetes:
      config:
         enableApi: true
```

_on purpose_ (and it is disabled by default), without actually specifying a namespace. Or extending some inner classes from `spring-cloud-kubernetes`.

So for example you could have done this: 

```
spring:
  cloud:
    kubernetes:
      config:
        #namespace: spring-k8s # <-- notice how this is NOT specified
        enableApi: true
        sources:
          - name: my-config-map
```

So simply providing that attribute should get rid of the problem too (which you should _anyway_).

Can you please provide your input here? thank you
