### ISSUE TITLE
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version

### ISSUE THREAD

**Issue by mbaykara** [spring-cloud/spring-cloud-kubernetes#949]
I saw a few issues with similar errors, however, each one was in a different use case. In my case, I am using `spring-cloud-starter-kubernetes-fabric8-config`  version `2.1.0`. 
#### Aim:
Reloading springboot properties while running in Kubernetes.
#### What I have done:
`1. step:` I added the following deps to the `pox.xml`
```
       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
         </dependency>
        <dependency>
    		<groupId>org.springframework.cloud</groupId>
    		<artifactId>spring-cloud-starter-kubernetes-fabric8-config</artifactId>
    		<version>2.1.0</version>
	</dependency>
```
`2. step:` Added `bootstrap.yml` and `application.yml`  to the resources

`3 step:` Added `@RefreshScope` to the java class where the properties going to be used.

So far it works as I expected and the application is running on Kubernetes and when I apply a new `configmap` then application is reloading the properties. So far so good. 
### Problem/Issue
When I check the application logs after the time (is not happening immediately) I see the following error:
```
2022-01-05 14:32:26.815  INFO 1 --- [://10.2.0.1/...] .f.c.r.EventBasedConfigMapChangeDetector : Added new Kubernetes watch: config-maps-watch-event
2022-01-05 14:32:26.815  INFO 1 --- [://10.2.0.1/...] .f.c.r.EventBasedConfigMapChangeDetector : Kubernetes event-based configMap change detector activated
2022-01-05 14:32:26.870  WARN 1 --- [://10.2.0.1/...] o.s.c.k.f.c.Fabric8ConfigUtils           : config-map with name : 'myapp-properties-kubernetes' not present in namespace : 'default'
2022-01-05 14:32:26.886  WARN 1 --- [://10.2.0.1/...] o.s.c.k.f.c.Fabric8ConfigUtils           : config-map with name : 'myapp-properties-kubernetes' not present in namespace : 'default'
2022-01-05 14:36:06.143  WARN 1 --- [://10.2.0.1/...] .f.c.r.EventBasedConfigMapChangeDetector : ConfigMaps watch closed

io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 3993633 (10593112)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:258) [kubernetes-client-4.13.3.jar:?]
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322) [okhttp-3.14.9.jar:?]
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219) [okhttp-3.14.9.jar:?]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105) [okhttp-3.14.9.jar:?]
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273) [okhttp-3.14.9.jar:?]
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209) [okhttp-3.14.9.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) [okhttp-3.14.9.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.14.9.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

2022-01-05 14:36:06.195  INFO 1 --- [://10.2.0.1/...] .f.c.r.EventBasedConfigMapChangeDetector : Added new Kubernetes watch: config-maps-watch-event
2022-01-05 14:36:06.195  INFO 1 --- [://10.2.0.1/...] .f.c.r.EventBasedConfigMapChangeDetector : Kubernetes event-based configMap change detector activated
```
The error above is not leading to any crashes, so the application is running properly. Still, I try to understand why this happening and how it will impact later?

**Comment by ryanjbaxter** [comment]
See https://github.com/spring-cloud/spring-cloud-kubernetes/pull/842

**Comment by mbaykara** [comment]
1. Yes it is just a warning ⚠ 
2. Reload is still working, I guess it is starting again after the fail above and it is happening approx. each 45-50 mins.(Please see above I extend the logs)
I am not calling k8s client in the app, I just injected the dependencies and reloaded the properties.

**Comment by ryanjbaxter** [comment]
It is likely not problematic, again it is just a warning.

Have you looked into using the configuration watcher as a better approach to reloading configuration?
https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#spring-cloud-kubernetes-configuration-watcher

**Comment by mbaykara** [comment]
I haven't tried yet but I will migrate to the watcher controller approaches asap. Thanks for the response!
