### ISSUE TITLE
Could not find class [org.springframework.cloud.client.loadbalancer.reactive.OnNoRibbonDefaultCondition]

### ISSUE THREAD

**Issue by lionchi** [spring-cloud/spring-cloud-kubernetes#972]
pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.3</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>ru.jpixel</groupId>
    <artifactId>discovery-service-with-kubernetes</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>discovery-service-with-kubernetes</name>
    <description>discovery-service-with-kubernetes</description>
    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>3.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-kubernetes-all</artifactId>
            <version>1.1.10.RELEASE</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

console log
```
"C:\Program Files\Java\jdk-17.0.2\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:61904,suspend=y,server=n -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -javaagent:C:\Users\Ivan\AppData\Local\JetBrains\IntelliJIdea2021.2\captureAgent\debugger-agent.jar -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -Dfile.encoding=UTF-8 -classpath "D:\MyProjects\discovery-service-with-kubernetes\target\classes;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-starter-web\2.6.3\spring-boot-starter-web-2.6.3.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-starter\2.6.3\spring-boot-starter-2.6.3.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-starter-logging\2.6.3\spring-boot-starter-logging-2.6.3.jar;C:\Users\Ivan\.m2\repository\ch\qos\logback\logback-classic\1.2.10\logback-classic-1.2.10.jar;C:\Users\Ivan\.m2\repository\ch\qos\logback\logback-core\1.2.10\logback-core-1.2.10.jar;C:\Users\Ivan\.m2\repository\org\apache\logging\log4j\log4j-to-slf4j\2.17.1\log4j-to-slf4j-2.17.1.jar;C:\Users\Ivan\.m2\repository\org\apache\logging\log4j\log4j-api\2.17.1\log4j-api-2.17.1.jar;C:\Users\Ivan\.m2\repository\org\slf4j\jul-to-slf4j\1.7.33\jul-to-slf4j-1.7.33.jar;C:\Users\Ivan\.m2\repository\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar;C:\Users\Ivan\.m2\repository\org\yaml\snakeyaml\1.29\snakeyaml-1.29.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-starter-json\2.6.3\spring-boot-starter-json-2.6.3.jar;C:\Users\Ivan\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.13.1\jackson-databind-2.13.1.jar;C:\Users\Ivan\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.13.1\jackson-annotations-2.13.1.jar;C:\Users\Ivan\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.13.1\jackson-core-2.13.1.jar;C:\Users\Ivan\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.13.1\jackson-datatype-jdk8-2.13.1.jar;C:\Users\Ivan\.m2\repository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.13.1\jackson-datatype-jsr310-2.13.1.jar;C:\Users\Ivan\.m2\repository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.13.1\jackson-module-parameter-names-2.13.1.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-starter-tomcat\2.6.3\spring-boot-starter-tomcat-2.6.3.jar;C:\Users\Ivan\.m2\repository\org\apache\tomcat\embed\tomcat-embed-core\9.0.56\tomcat-embed-core-9.0.56.jar;C:\Users\Ivan\.m2\repository\org\apache\tomcat\embed\tomcat-embed-el\9.0.56\tomcat-embed-el-9.0.56.jar;C:\Users\Ivan\.m2\repository\org\apache\tomcat\embed\tomcat-embed-websocket\9.0.56\tomcat-embed-websocket-9.0.56.jar;C:\Users\Ivan\.m2\repository\org\springframework\spring-web\5.3.15\spring-web-5.3.15.jar;C:\Users\Ivan\.m2\repository\org\springframework\spring-beans\5.3.15\spring-beans-5.3.15.jar;C:\Users\Ivan\.m2\repository\org\springframework\spring-webmvc\5.3.15\spring-webmvc-5.3.15.jar;C:\Users\Ivan\.m2\repository\org\springframework\spring-aop\5.3.15\spring-aop-5.3.15.jar;C:\Users\Ivan\.m2\repository\org\springframework\spring-context\5.3.15\spring-context-5.3.15.jar;C:\Users\Ivan\.m2\repository\org\springframework\spring-expression\5.3.15\spring-expression-5.3.15.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-devtools\2.6.3\spring-boot-devtools-2.6.3.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot\2.6.3\spring-boot-2.6.3.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-autoconfigure\2.6.3\spring-boot-autoconfigure-2.6.3.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-starter-actuator\2.6.3\spring-boot-starter-actuator-2.6.3.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-actuator-autoconfigure\2.6.3\spring-boot-actuator-autoconfigure-2.6.3.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-actuator\2.6.3\spring-boot-actuator-2.6.3.jar;C:\Users\Ivan\.m2\repository\io\micrometer\micrometer-core\1.8.2\micrometer-core-1.8.2.jar;C:\Users\Ivan\.m2\repository\org\hdrhistogram\HdrHistogram\2.1.12\HdrHistogram-2.1.12.jar;C:\Users\Ivan\.m2\repository\org\latencyutils\LatencyUtils\2.0.3\LatencyUtils-2.0.3.jar;C:\Users\Ivan\.m2\repository\org\projectlombok\lombok\1.18.22\lombok-1.18.22.jar;C:\Users\Ivan\.m2\repository\org\slf4j\slf4j-api\1.7.33\slf4j-api-1.7.33.jar;C:\Users\Ivan\.m2\repository\jakarta\xml\bind\jakarta.xml.bind-api\2.3.3\jakarta.xml.bind-api-2.3.3.jar;C:\Users\Ivan\.m2\repository\jakarta\activation\jakarta.activation-api\1.2.2\jakarta.activation-api-1.2.2.jar;C:\Users\Ivan\.m2\repository\org\springframework\spring-core\5.3.15\spring-core-5.3.15.jar;C:\Users\Ivan\.m2\repository\org\springframework\spring-jcl\5.3.15\spring-jcl-5.3.15.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-starter-openfeign\3.1.0\spring-cloud-starter-openfeign-3.1.0.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-starter\3.1.0\spring-cloud-starter-3.1.0.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-context\3.1.0\spring-cloud-context-3.1.0.jar;C:\Users\Ivan\.m2\repository\org\springframework\security\spring-security-rsa\1.0.10.RELEASE\spring-security-rsa-1.0.10.RELEASE.jar;C:\Users\Ivan\.m2\repository\org\bouncycastle\bcpkix-jdk15on\1.68\bcpkix-jdk15on-1.68.jar;C:\Users\Ivan\.m2\repository\org\bouncycastle\bcprov-jdk15on\1.68\bcprov-jdk15on-1.68.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-openfeign-core\3.1.0\spring-cloud-openfeign-core-3.1.0.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-starter-aop\2.6.3\spring-boot-starter-aop-2.6.3.jar;C:\Users\Ivan\.m2\repository\org\aspectj\aspectjweaver\1.9.7\aspectjweaver-1.9.7.jar;C:\Users\Ivan\.m2\repository\io\github\openfeign\form\feign-form-spring\3.8.0\feign-form-spring-3.8.0.jar;C:\Users\Ivan\.m2\repository\io\github\openfeign\form\feign-form\3.8.0\feign-form-3.8.0.jar;C:\Users\Ivan\.m2\repository\commons-fileupload\commons-fileupload\1.4\commons-fileupload-1.4.jar;C:\Users\Ivan\.m2\repository\commons-io\commons-io\2.2\commons-io-2.2.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-commons\3.1.0\spring-cloud-commons-3.1.0.jar;C:\Users\Ivan\.m2\repository\org\springframework\security\spring-security-crypto\5.6.1\spring-security-crypto-5.6.1.jar;C:\Users\Ivan\.m2\repository\io\github\openfeign\feign-core\11.7\feign-core-11.7.jar;C:\Users\Ivan\.m2\repository\io\github\openfeign\feign-slf4j\11.7\feign-slf4j-11.7.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-starter-kubernetes-all\1.1.10.RELEASE\spring-cloud-starter-kubernetes-all-1.1.10.RELEASE.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-kubernetes-core\1.1.10.RELEASE\spring-cloud-kubernetes-core-1.1.10.RELEASE.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-client\4.13.2\kubernetes-client-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-core\4.13.2\kubernetes-model-core-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-common\4.13.2\kubernetes-model-common-4.13.2.jar;C:\Users\Ivan\.m2\repository\com\fasterxml\jackson\module\jackson-module-jaxb-annotations\2.13.1\jackson-module-jaxb-annotations-2.13.1.jar;C:\Users\Ivan\.m2\repository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;C:\Users\Ivan\.m2\repository\javax\xml\bind\jaxb-api\2.3.1\jaxb-api-2.3.1.jar;C:\Users\Ivan\.m2\repository\javax\activation\javax.activation-api\1.2.0\javax.activation-api-1.2.0.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-rbac\4.13.2\kubernetes-model-rbac-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-admissionregistration\4.13.2\kubernetes-model-admissionregistration-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-apps\4.13.2\kubernetes-model-apps-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-autoscaling\4.13.2\kubernetes-model-autoscaling-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-apiextensions\4.13.2\kubernetes-model-apiextensions-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-batch\4.13.2\kubernetes-model-batch-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-certificates\4.13.2\kubernetes-model-certificates-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-coordination\4.13.2\kubernetes-model-coordination-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-discovery\4.13.2\kubernetes-model-discovery-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-events\4.13.2\kubernetes-model-events-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-extensions\4.13.2\kubernetes-model-extensions-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-networking\4.13.2\kubernetes-model-networking-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-metrics\4.13.2\kubernetes-model-metrics-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-policy\4.13.2\kubernetes-model-policy-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-scheduling\4.13.2\kubernetes-model-scheduling-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-settings\4.13.2\kubernetes-model-settings-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-storageclass\4.13.2\kubernetes-model-storageclass-4.13.2.jar;C:\Users\Ivan\.m2\repository\io\fabric8\kubernetes-model-node\4.13.2\kubernetes-model-node-4.13.2.jar;C:\Users\Ivan\.m2\repository\com\squareup\okhttp3\okhttp\3.14.9\okhttp-3.14.9.jar;C:\Users\Ivan\.m2\repository\com\squareup\okio\okio\1.17.2\okio-1.17.2.jar;C:\Users\Ivan\.m2\repository\com\squareup\okhttp3\logging-interceptor\3.14.9\logging-interceptor-3.14.9.jar;C:\Users\Ivan\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-yaml\2.13.1\jackson-dataformat-yaml-2.13.1.jar;C:\Users\Ivan\.m2\repository\io\fabric8\zjsonpatch\0.3.0\zjsonpatch-0.3.0.jar;C:\Users\Ivan\.m2\repository\com\github\mifmif\generex\1.0.2\generex-1.0.2.jar;C:\Users\Ivan\.m2\repository\dk\brics\automaton\automaton\1.11-8\automaton-1.11-8.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-kubernetes-config\1.1.10.RELEASE\spring-cloud-kubernetes-config-1.1.10.RELEASE.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-kubernetes-discovery\1.1.10.RELEASE\spring-cloud-kubernetes-discovery-1.1.10.RELEASE.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-kubernetes-ribbon\1.1.10.RELEASE\spring-cloud-kubernetes-ribbon-1.1.10.RELEASE.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-kubernetes-loadbalancer\1.1.10.RELEASE\spring-cloud-kubernetes-loadbalancer-1.1.10.RELEASE.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-starter-loadbalancer\2.2.9.RELEASE\spring-cloud-starter-loadbalancer-2.2.9.RELEASE.jar;C:\Users\Ivan\.m2\repository\org\springframework\cloud\spring-cloud-loadbalancer\2.2.9.RELEASE\spring-cloud-loadbalancer-2.2.9.RELEASE.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-starter-validation\2.6.3\spring-boot-starter-validation-2.6.3.jar;C:\Users\Ivan\.m2\repository\org\hibernate\validator\hibernate-validator\6.2.0.Final\hibernate-validator-6.2.0.Final.jar;C:\Users\Ivan\.m2\repository\jakarta\validation\jakarta.validation-api\2.0.2\jakarta.validation-api-2.0.2.jar;C:\Users\Ivan\.m2\repository\org\jboss\logging\jboss-logging\3.4.3.Final\jboss-logging-3.4.3.Final.jar;C:\Users\Ivan\.m2\repository\com\fasterxml\classmate\1.5.1\classmate-1.5.1.jar;C:\Users\Ivan\.m2\repository\io\projectreactor\reactor-core\3.4.14\reactor-core-3.4.14.jar;C:\Users\Ivan\.m2\repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;C:\Users\Ivan\.m2\repository\io\projectreactor\addons\reactor-extra\3.4.6\reactor-extra-3.4.6.jar;C:\Users\Ivan\.m2\repository\org\springframework\boot\spring-boot-starter-cache\2.6.3\spring-boot-starter-cache-2.6.3.jar;C:\Users\Ivan\.m2\repository\org\springframework\spring-context-support\5.3.15\spring-context-support-5.3.15.jar;C:\Users\Ivan\.m2\repository\com\stoyanr\evictor\1.0.0\evictor-1.0.0.jar;C:\Users\Ivan\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.1\lib\idea_rt.jar" ru.jpixel.discoveryservicewithkubernetes.DiscoveryServiceWithKubernetesApplication
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Connected to the target VM, address: '127.0.0.1:61904', transport: 'socket'
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
19:51:12.809 [Thread-0] DEBUG org.springframework.boot.devtools.restart.classloader.RestartClassLoader - Created RestartClassLoader org.springframework.boot.devtools.restart.classloader.RestartClassLoader@6c8d18b8

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.3)

2022-02-12 19:51:14,407 INFO  [background-preinit] ip[] org.hibernate.validator.internal.util.Version (21):
                HV000001: Hibernate Validator 6.2.0.Final
2022-02-12 19:51:14,418 INFO  [restartedMain] ip[] org.springframework.boot.StartupInfoLogger (55):
                Starting DiscoveryServiceWithKubernetesApplication using Java 17.0.2 on DESKTOP-AR3TBUT with PID 13380 (D:\MyProjects\discovery-service-with-kubernetes\target\classes started by Ivan in D:\MyProjects\discovery-service-with-kubernetes)
2022-02-12 19:51:14,419 INFO  [restartedMain] ip[] org.springframework.boot.SpringApplication (637):
                No active profile set, falling back to default profiles: default
2022-02-12 19:51:14,448 INFO  [restartedMain] ip[] org.springframework.boot.logging.DeferredLog (255):
                Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2022-02-12 19:51:14,448 INFO  [restartedMain] ip[] org.springframework.boot.logging.DeferredLog (255):
                For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2022-02-12 19:51:14,768 WARN  [restartedMain] ip[] org.springframework.context.support.AbstractApplicationContext (591):
                Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [ru.jpixel.discoveryservicewithkubernetes.DiscoveryServiceWithKubernetesApplication]; nested exception is java.lang.IllegalArgumentException: Could not find class [org.springframework.cloud.client.loadbalancer.reactive.OnNoRibbonDefaultCondition]
2022-02-12 19:51:14,775 INFO  [restartedMain] ip[] org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener (136):
                

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-02-12 19:51:14,790 ERROR [restartedMain] ip[] org.springframework.boot.SpringApplication (821):
                Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [ru.jpixel.discoveryservicewithkubernetes.DiscoveryServiceWithKubernetesApplication]; nested exception is java.lang.IllegalArgumentException: Could not find class [org.springframework.cloud.client.loadbalancer.reactive.OnNoRibbonDefaultCondition]
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:610)
	at org.springframework.context.annotation.ConfigurationClassParser.access$800(ConfigurationClassParser.java:111)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.lambda$processGroupImports$1(ConfigurationClassParser.java:812)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809)
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at ru.jpixel.discoveryservicewithkubernetes.DiscoveryServiceWithKubernetesApplication.main(DiscoveryServiceWithKubernetesApplication.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.IllegalArgumentException: Could not find class [org.springframework.cloud.client.loadbalancer.reactive.OnNoRibbonDefaultCondition]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:334)
	at org.springframework.context.annotation.ConditionEvaluator.getCondition(ConditionEvaluator.java:124)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:96)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:226)
	at org.springframework.context.annotation.ConfigurationClassParser.processMemberClasses(ConfigurationClassParser.java:372)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:272)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:600)
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.client.loadbalancer.reactive.OnNoRibbonDefaultCondition
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.springframework.boot.devtools.restart.classloader.RestartClassLoader.loadClass(RestartClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:324)
	... 31 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:61904', transport: 'socket'

Process finished with exit code 0

```

What could be the problem ? Could it be because of spring boot version 2.6.3 and because of java version 17? If so, which versions should I use?

**Comment by ryanjbaxter** [comment]
Please use the spring cloud bom as it will pull in the correct version dependencies for you.  That version of spring cloud kubernetes is not compatible with the version of spring boot or other spring cloud projects you are using
