### ISSUE TITLE
Random logs with Spring Boot 2.6.4 and Spring Cloud Kubernetes 2021.0.0

### ISSUE THREAD

**Issue by Abhi-Codes** [spring-cloud/spring-cloud-kubernetes#978]
**Describe the bug**
Spring Boot 2.6.4
Spring Cloud 2021.0.0

I have deployed Spring Boot application on Kubernetes and provided explicit config map and secret name in bootstrap yaml, it is able to correctly pick up properties from config map and secrets . But I see random logs that its not able to read config map and secret having name spring boot app name-dev and spring boot app name-kubernetes . How do I disable these unnecessary logs .

With Spring Boot 2.5.10 and Spring Cloud 2020.0.3 , I was not facing this issue. 

Bootstrap yaml 

```
spring:
  config:
    activate:
      on-profile:
      - dev
  cloud:
    vault:
      uri: https://xxx.com/
      app-role:
        role-id: 75
        secret-id: c4
---

management:
  endpoints:
    web:
      exposure:
        include: restart,health
  endpoint:
    health:
      probes:
        enabled: true
    restart:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true      
  server:
    port: 8081
spring: 
  cloud:
    kubernetes:
      config: 
        enabled: true
        name: ep-console-service-config
      reload: 
        enabled: true
        monitoring-config-maps: true
#        monitoring-secrets: true
        strategy: RESTART_CONTEXT
#      secrets:
#        enable-api: true
#        enabled: true 
#        name: ep-console-service-secret
    discovery:
      enabled: false
    vault:
      authentication: approle
      enabled: true
      kv:
        backend: ep
        enabled: true
  application:
    name: ep-console-service 
```

**Comment by ryanjbaxter** [comment]
Can you try using Spring Cloud 2021.0.1?

**Comment by wind57** [comment]
can you actually show the exact logs you get? There was very recently that we debated to show or not some logs, and moved them to debug mode; but may be there is more needed. 

So the ask from Ryan is simple: upgrade to the latest spring-cloud; if the problem persists - show the exact logs and let's see from there. thank you.

**Comment by Abhi-Codes** [comment]
I upgraded to Spring Cloud 2020.0.1 but I am still seeing these logs. 

Bootstrap.yaml

```
management:
  endpoints:
    web:
      exposure:
        include: restart,health
  endpoint:
    health:
      probes:
        enabled: true
    restart:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true      
  server:
    port: 8081
spring: 
  application:
    name: ecms-bcp-sendgrid-service
  cloud: 
    kubernetes: 
      config: 
        enabled: true
        name: ecms-bcp-sendgrid-service-config
      reload: 
        enabled: true
        monitoring-config-maps: true
        monitoring-secrets: true
        strategy: RESTART_CONTEXT
      secrets:
        enable-api: true
        enabled: true 
        name: ecms-bcp-sendgrid-service-secret
```

Logs


```
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.58.jar!/:na]
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.58.jar!/:na]
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.58.jar!/:na]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.58.jar!/:na]
at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2022-02-27 04:26:48.076 WARN 1 --- [/172.24.0.1/...] .f.c.r.EventBasedConfigMapChangeDetector : ConfigMaps watch closed

io.fabric8.kubernetes.client.WatcherException: too old resource version: 356638363 (359844050)
at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onStatus(AbstractWatchManager.java:273) ~[kubernetes-client-5.9.0.jar!/:na]
at io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager.onMessage(AbstractWatchManager.java:257) ~[kubernetes-client-5.9.0.jar!/:na]
at io.fabric8.kubernetes.client.dsl.internal.WatcherWebSocketListener.onMessage(WatcherWebSocketListener.java:93) ~[kubernetes-client-5.9.0.jar!/:na]
at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322) ~[okhttp-3.14.9.jar!/:na]
at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219) ~[okhttp-3.14.9.jar!/:na]
at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105) ~[okhttp-3.14.9.jar!/:na]
at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273) ~[okhttp-3.14.9.jar!/:na]
at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209) ~[okhttp-3.14.9.jar!/:na]
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) ~[okhttp-3.14.9.jar!/:na]
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.14.9.jar!/:na]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 356638363 (359844050)
... 13 common frames omitted

2022-02-27 04:26:48.370 INFO 1 --- [/172.24.0.1/...] .f.c.r.EventBasedConfigMapChangeDetector : Added new Kubernetes watch: config-maps-watch-event
2022-02-27 04:26:48.371 INFO 1 --- [/172.24.0.1/...] .f.c.r.EventBasedConfigMapChangeDetector : Kubernetes event-based configMap change detector activated
2022-02-27 04:26:48.679 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-kubernetes' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:48.765 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-dev' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:48.779 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-kubernetes' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:48.866 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-dev' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:48.966 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-kubernetes' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:48.975 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-dev' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:49.080 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-kubernetes' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:49.165 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-dev' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:49.266 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-kubernetes' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:49.275 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-dev' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:49.381 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-kubernetes' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:49.466 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-dev' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:49.570 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-kubernetes' not present in namespace : 'ecms-bcp-dev'
2022-02-27 04:26:49.577 INFO 1 --- [/172.24.0.1/...] o.s.c.k.f.config.Fabric8ConfigUtils : config-map with name : 'ecms-bcp-sendgrid-service-config-dev' not present in namespace : 'ecms-bcp-dev'
```

**Comment by Abhi-Codes** [comment]
[ecms-bcp-sendgrid-service-6665fd74c6-4466c.log](https://github.com/spring-cloud/spring-cloud-kubernetes/files/8148055/ecms-bcp-sendgrid-service-6665fd74c6-4466c.log)

Pasting entire log.

**Comment by wind57** [comment]
> These logs keep on being generated , if you see my bootstrap yaml , I haven't even mentioned the config maps and secrets with these name .

right. This is something that we read as part of "profile-based" sources and is pretty much expected. So the fact that we _try_ to read those sources is expected, but the fact that the logs are on _info_ level is probably not a good thing, indeed. I'll change them to `warn`, especially since the secrets implementation does that on `warn` too. 

The thing that I don't quite understand is why there are so many logs, there should be only two: one for `ecms-bcp-sendgrid-service-config-kubernetes` and one for `ecms-bcp-sendgrid-service-config-dev`. Weird, but let's fix this one at a time...

[PR for this](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/980)

**Comment by alicedaydream** [comment]
Hi guys,
Is the fix for this issue in `org.springframework.cloud:spring-cloud-dependencies` version`2021.0.2`? Do you know when that will be released?

**Comment by mikaello** [comment]
> Hi guys, Is the fix for this issue in `org.springframework.cloud:spring-cloud-dependencies` version`2021.0.2`? Do you know when that will be released https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies? 

I can't see it on `mvnrepository.com`, but I am able to pull it now, so it seems to be released:

```shell
mvn dependency:get -Dartifact=org.springframework.cloud:spring-cloud-dependencies:2021.0.2 -Dpackaging=pom
```
